// Copies the JSON the app needs from ../data into public/data/<name>.<sha256:8>.json and writes
// src/generated/data-manifest.ts so the bundle knows the content-hashed URLs (under the
// /australia/ base) without an extra round trip. Also copies the shared design tokens.
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const BASE_PATH = '/australia/'
const here = dirname(fileURLToPath(import.meta.url))
const appDir = resolve(here, '..')
const dataDir = resolve(appDir, '..', 'data')
const outDir = join(appDir, 'public', 'data')
const genDir = join(appDir, 'src', 'generated')

const files = {}
for (const name of ['songs', 'places', 'facets', 'sources']) {
  const p = join(dataDir, `${name}.json`)
  if (!existsSync(p)) {
    console.error(`sync-data: ${p} not found. The dataset must be committed under australia/data/.`)
    process.exit(1)
  }
  files[name] = { text: JSON.stringify(JSON.parse(readFileSync(p, 'utf8'))), source: `${name}.json` }
}

rmSync(outDir, { recursive: true, force: true })
mkdirSync(outDir, { recursive: true })
mkdirSync(genDir, { recursive: true })

const manifest = {}
const report = []
for (const [name, { text, source }] of Object.entries(files)) {
  const hash = createHash('sha256').update(text).digest('hex').slice(0, 8)
  const rel = `${name}.${hash}.json`
  writeFileSync(join(outDir, rel), text)
  manifest[name] = `${BASE_PATH}data/${rel}`
  report.push(`  ${name.padEnd(8)} <- ${source} (${(text.length / 1024).toFixed(0)} KB) -> ${rel}`)
}

const ts = `// Generated by scripts/sync-data.mjs. Do not edit; do not commit.
export const dataManifest = ${JSON.stringify(manifest, null, 2)} as const
export type DataFileName = keyof typeof dataManifest
`
writeFileSync(join(genDir, 'data-manifest.ts'), ts)

// tokens: single source of truth is ../../app-tokens/tokens.css (shared with the Bartok app)
const tokensSrc = resolve(appDir, '..', '..', 'app-tokens', 'tokens.css')
if (!existsSync(tokensSrc)) {
  console.error(`sync-data: ${tokensSrc} not found.`)
  process.exit(1)
}
writeFileSync(join(genDir, 'tokens.css'), readFileSync(tokensSrc, 'utf8'))
console.log(`sync-data:\n${report.join('\n')}\n  tokens   <- app-tokens/tokens.css`)
