/* eslint-disable */
// Generated by scripts/gen-types.mjs from data/schema/facets.schema.json. Do not edit by hand.

/**
 * facets.json: for each facet, a map of value -> number of songs. Keys are sorted. Null values are counted under the key 'null'.
 */
export interface Facets {
  _meta: {
    songCount: number
    sites: CountMap
    builtWith?: string | null
  }
  genre: CountMap
  style: CountMap
  performance: CountMap
  instrument: CountMap
  year: CountMap
  country: CountMap
  region: CountMap
  county: CountMap
  village: CountMap
  collector: CountMap
  ethnicity: CountMap
  site: CountMap
  [k: string]:
    | CountMap
    | {
        songCount: number
        sites: CountMap
        builtWith?: string | null
      }
    | undefined
}
export interface CountMap {
  [k: string]: number | undefined
}
