/* eslint-disable */
// Generated by scripts/gen-types.mjs from data/schema/place.schema.json. Do not edit by hand.

/**
 * One node of the place hierarchy in places.json (country > region > county > village). places.json is an array of these nodes sorted by id; the app rebuilds the tree from `parent`.
 */
export interface Place {
  /**
   * Slash-joined slug path, e.g. 'ro', 'ro/crisana', 'ro/crisana/bihor', 'ro/crisana/bihor/beius'. Unresolved localities live under '<country or xx>/unresolved/<slug>'.
   */
  id: string
  type: 'country' | 'region' | 'county' | 'village'
  /**
   * Modern name (Romanian with diacritics for RO).
   */
  name: string
  /**
   * Historical (usually Hungarian) name as printed on the source sites.
   */
  nameHistorical: string | null
  /**
   * Id of the parent node; null for a country.
   */
  parent: string | null
  /**
   * ISO 3166-1 alpha-2, or null when unresolved.
   */
  country: string | null
  region: string | null
  /**
   * Modern county name.
   */
  county: string | null
  countyHistorical: string | null
  lat: number | null
  lng: number | null
  /**
   * Where lat/lng came from. 'gazetteer-approx' coordinates are seeds to be verified.
   */
  coordSource: 'site' | 'gazetteer-approx' | 'centroid-of-children' | null
  counts: {
    total: number
    byGenre: CountMap
    byPerformance: CountMap
    bySite: CountMap
  }
  years: {
    min: number | null
    max: number | null
  }
  /**
   * Ids of songs located directly at this node (villages only; aggregates use counts).
   */
  songIds: string[]
  /**
   * Gazetteer confidence for the modern-name/coordinate match.
   */
  confidence?: 'high' | 'medium' | 'low' | null
}
export interface CountMap {
  [k: string]: number | undefined
}
