/* eslint-disable */
// Generated by scripts/gen-types.mjs from data/schema/song.schema.json. Do not edit by hand.

/**
 * Canonical record for one melody scraped from a HUN-REN BTK ZTI Bartok database. Unknown values are null, never invented. Arrays are empty when nothing is known.
 */
export interface Song {
  /**
   * Stable id: site prefix + site record id. Prefixes: fmbc (bartok-nepzene.zti.hu), bsys (systems.zti.hu/br), gyuj (bartok-gyujtesek.zti.hu), rfm (printed Rumanian Folk Music volumes via the Internet Archive scans, see docs/PRINT-SOURCES.md).
   */
  id: string
  source: {
    site: 'fmbc' | 'bsys' | 'gyuj' | 'rfm'
    /**
     * Human-readable name of the source database, for attribution (e.g. 'Folk Music in Bartok's Compositions (HUN-REN BTK ZTI)').
     */
    siteName: string
    /**
     * The site's own record identifier as displayed (reference code, system position or URL id). Required: academic integrity.
     */
    siteId: string
    /**
     * Canonical record page URL on the source site, exactly as fetched. Never synthesised.
     */
    url: string
    /**
     * The site's own reference code, e.g. an RFM or Bartok System number, verbatim.
     */
    referenceCode: string | null
    /**
     * Published volume the melody appears in (e.g. RFM I, Bihor 1913), verbatim.
     */
    volume: string | null
    /**
     * Number within the volume or the site's numeric record id, verbatim.
     */
    number: string | null
    /**
     * Raw record id as it appears in the site URL or markup.
     */
    siteRecordId?: string | null
    /**
     * When the page was fetched (from the HTML cache sidecar).
     */
    fetchedAt?: string | null
    /**
     * The same underlying record on another site (bsys and gyuj share backend record ids). Each keeps its own link for attribution.
     */
    alternates: {
      site: 'fmbc' | 'bsys' | 'gyuj'
      siteName?: string | null
      siteId: string
      url: string
      /**
       * The id this record had when it was a separate record (e.g. gyuj-1-12994 before merging into bsys-10-12994); lets older references be mapped.
       */
      id?: string | null
    }[]
  }
  /**
   * Display title. For text-bearing songs usually the first line; for instrumental pieces the site's title or genre label.
   */
  title: string | null
  /**
   * Text incipit (first line of the sung text) if given separately from the title.
   */
  incipit: string | null
  /**
   * Controlled vocabulary. null only when the site gives no genre label at all; 'other' when a label exists but maps to nothing.
   */
  genre: 'colinda' | 'doina' | 'bocet' | 'cantec' | 'joc' | 'nunta' | 'other' | null
  /**
   * The site's original genre label, verbatim.
   */
  genreRaw: string | null
  /**
   * Stylistic class for sorting/filtering, normalised: 'old style' (Bartok System class A), 'new style' (class B), 'mixed style' (class C), 'instrumental', 'not classified', or a site label. null when the site gives nothing.
   */
  style: string | null
  performance: 'vocal' | 'instrumental' | 'mixed' | 'unknown'
  /**
   * Canonical instrument names (lowercase English, e.g. violin, fluier, bagpipe). Empty when vocal or unknown.
   */
  instrument: string[]
  performer: {
    name: string | null
    age: number | null
    sex: 'm' | 'f' | null
    /**
     * As stated by the site (e.g. Romanian, Hungarian, Slovak), whitespace-normalised.
     */
    ethnicity: string | null
  }
  /**
   * Collector name, usually Bartok Bela; verbatim.
   */
  collector: string | null
  collected: {
    /**
     * Year of collection. The Bartok System also holds 19th-century collections (from 1865), hence the wide range.
     */
    year: number | null
    month: number | null
    day: number | null
    /**
     * The date string as printed on the site.
     */
    raw: string | null
  }
  location: {
    /**
     * ISO 3166-1 alpha-2 of the modern country (RO, HU, SK, RS, UA, ...), derived from the modern county via the gazetteer.
     */
    country: string | null
    /**
     * Historical region within the modern country, e.g. Transylvania, Banat, Crisana, Maramures.
     */
    region: string | null
    /**
     * Modern county name (Romanian spelling with diacritics).
     */
    county: string | null
    /**
     * Historical (Hungarian) county name as used on the site, e.g. Bihar, Hunyad.
     */
    countyHistorical: string | null
    /**
     * Modern locality name with diacritics.
     */
    village: string | null
    /**
     * Locality name as printed on the site, usually the Hungarian historical name.
     */
    villageHistorical: string | null
    lat: number | null
    lng: number | null
    /**
     * The full place string as printed on the site, including any 'A / B' origin notation.
     */
    raw: string | null
    /**
     * Id of the matching node in places.json, when resolved.
     */
    placeId?: string | null
    /**
     * For sites that print 'collection place / informant origin' (A / B): the B part, resolved the same way.
     */
    origin?: {
      village?: string | null
      villageHistorical?: string | null
      county?: string | null
      countyHistorical?: string | null
      placeId?: string | null
    } | null
    /**
     * How modern names and coordinates were obtained: site = printed by the source site (incl. map coordinates); gazetteer = village matched in data/gazetteer.json; county = village unmatched but the historical county lies wholly in one present-day country (country/region/county derived, no coordinates); unresolved = only the printed names are known.
     */
    resolution?: 'site' | 'gazetteer' | 'county' | 'manual' | 'unresolved' | null
  }
  media: {
    notation: MediaItem[]
    audio: MediaItem[]
  }
  music: {
    /**
     * Position in the Bartok System (e.g. 'A 204/3') or the site's equivalent class number.
     */
    systemPosition: string | null
    /**
     * Line-ending cadence degrees as printed, e.g. '5 (b3) 1'.
     */
    cadences: string | null
    /**
     * Rhythm type or rhythm table flattened to text (parlando, giusto, tempo giusto, etc.).
     */
    rhythm: string | null
    /**
     * Scale or mode label as printed.
     */
    mode: string | null
    /**
     * Range as printed, e.g. '1-8' or 'VII-6'.
     */
    ambitus: string | null
    /**
     * Syllable count per line as printed, e.g. '8,8,8,8'.
     */
    syllables: string | null
    /**
     * Line structure as printed, e.g. 'A B B A' or 'A5 A5 A A'.
     */
    form: string | null
  }
  /**
   * Full sung text, lines separated by newline.
   */
  text: string | null
  remarks: string | null
  related: {
    /**
     * Id of a record in songs.json, when the link could be resolved.
     */
    id: string | null
    url: string | null
    label: string | null
    relation: 'variant' | 'same-source' | 'same-informant' | 'same-place' | 'cross-site' | 'link'
  }[]
  /**
   * Bartok works that use this melody (site 1 only). Empty for the other sites.
   */
  composition: {
    /**
     * Work title, e.g. 'Romanian Folk Dances'.
     */
    work: string | null
    /**
     * Movement or number within the work, e.g. 'No. 3, Pe loc'.
     */
    movement: string | null
    /**
     * Catalogue number (Sz., BB, DD) as printed.
     */
    catalogue: string | null
    raw: string | null
  }[]
  /**
   * Label -> value pairs exactly as extracted from the page, for the Raw JSON tab and for debugging the mapping. Optional.
   */
  rawFields?: {
    [k: string]: string | null | undefined
  } | null
  /**
   * The site's own style/class wording, e.g. 'Class A: old style > I. parlando-rubato or fixed rhythm > number of syllables: 8', verbatim.
   */
  styleRaw: string | null
  /**
   * The collecting trip (bartok-gyujtesek.zti.hu collection) the record belongs to, when known.
   */
  journey: {
    collectionId: string | null
    /**
     * e.g. 'February, 1910. Upper region of the river Fekete-Koros: district of Belenyes and Vaskoh'
     */
    label: string | null
    dateRaw?: string | null
    place?: string | null
    url?: string | null
  } | null
}
export interface MediaItem {
  url: string
  /**
   * MIME type or short kind (image/png, audio/mpeg, pdf).
   */
  type: string | null
  caption: string | null
}
