// Small journeys / villages / context-events fixture for the journey mapper tests. Song ids
// and place ids match src/test/fixtures/songs.small.json and places.small.json.
import type { ContextEvent, Journey, VillagesFile } from './journeys'

const departure: Journey['departure'] = {
  name: 'Budapest',
  lat: 47.4979,
  lng: 19.0402,
  confidence: 'assumed',
  note: 'Default departure point: Budapest. Not documented per trip; the UI labels it as assumed.',
}

const facts = (over: Partial<Journey['facts']> = {}): Journey['facts'] => ({
  villages: 0,
  counties: [],
  countiesHistorical: [],
  ethnicGroups: {},
  instruments: {},
  genres: {},
  performers: 0,
  ...over,
})

export const fixtureJourneys: Journey[] = [
  {
    id: 'gyuj-50',
    derivedFrom: 'gyuj-collections',
    kind: 'cluster',
    collector: 'Bartok Bela',
    label: 'July-August, 1909. Upper region of the river Fekete-Koros',
    labelDateRaw: 'July-August, 1909',
    labelPlaceRaw: 'Upper region of the river Fekete-Koros',
    sourceUrl: 'https://bartok-gyujtesek.zti.hu/en/browse/50',
    countOnline: null,
    recordsOnline: false,
    dateStart: '1909-07',
    dateEnd: '1909-08',
    dateConfidence: 'month',
    datePeriods: [{ start: '1909-07', end: '1909-08', precision: 'month', qualifiers: [], raw: 'July-August, 1909', uncertain: false }],
    recordDateRange: null,
    days: null,
    departure,
    stops: [
      {
        seq: 1,
        placeId: null,
        village: 'Crisul Negru valley',
        villageHistorical: 'Fekete-Koros volgye',
        county: 'Bihor',
        countyHistorical: 'Bihar',
        country: 'RO',
        lat: 46.6,
        lng: 22.3,
        arrival: '1909-07',
        departure: '1909-08',
        recordCount: 0,
        songIds: [],
        kmFromPrevious: null,
        locationConfidence: 'label-region',
      },
    ],
    distanceKm: null,
    recordCount: 0,
    facts: facts({ counties: ['Bihor'], countiesHistorical: ['Bihar'], villages: 1 }),
    songIds: [],
    nowIn: ['RO'],
    romanianMaterial: { value: true, confidence: 'documented' },
    derivation: { gapDays: 10, jumpKm: 250, splitReasons: ['collection'], generator: 'test', attachedRecords: { byMembership: 0, byDateCounty: 0 } },
  },
  {
    id: 'J-1910-00-01',
    derivedFrom: 'date-gap',
    kind: 'cluster',
    collector: 'Bartók Béla',
    label: null,
    labelDateRaw: null,
    labelPlaceRaw: null,
    sourceUrl: null,
    countOnline: null,
    recordsOnline: true,
    dateStart: '1910',
    dateEnd: '1910',
    dateConfidence: 'year',
    datePeriods: [{ start: '1910', end: '1910', precision: 'year', qualifiers: [], raw: null, uncertain: false }],
    recordDateRange: { start: '1910', end: '1910' },
    days: null,
    departure,
    stops: [
      {
        seq: 1,
        placeId: 'ro/transylvania/cluj/izvoru-crisului',
        village: 'Izvoru Crișului',
        villageHistorical: 'Körösfő',
        county: 'Cluj',
        countyHistorical: 'Kolozs',
        country: 'RO',
        lat: 46.84,
        lng: 23.05,
        arrival: '1910',
        departure: '1910',
        recordCount: 1,
        songIds: ['bsys-17'],
        kmFromPrevious: null,
        locationConfidence: 'resolved',
      },
    ],
    distanceKm: null,
    recordCount: 1,
    facts: facts({ counties: ['Cluj'], countiesHistorical: ['Kolozs'], villages: 1 }),
    songIds: ['bsys-17'],
    nowIn: ['RO'],
    romanianMaterial: null,
    derivation: { gapDays: 10, jumpKm: 250, splitReasons: ['year'], generator: 'test' },
  },
  {
    id: 'J-1910-07-01',
    derivedFrom: 'date-gap',
    kind: 'route',
    collector: 'Bartók Béla',
    label: null,
    labelDateRaw: null,
    labelPlaceRaw: null,
    sourceUrl: null,
    countOnline: null,
    recordsOnline: true,
    dateStart: '1910-07-03',
    dateEnd: '1910-07-08',
    dateConfidence: 'day',
    datePeriods: [{ start: '1910-07-03', end: '1910-07-08', precision: 'day', qualifiers: [], raw: null, uncertain: false }],
    recordDateRange: { start: '1910-07-03', end: '1910-07-08' },
    days: 6,
    departure,
    stops: [
      {
        seq: 1,
        placeId: 'ro/crisana/bihor/beius',
        village: 'Beiuș',
        villageHistorical: 'Belényes',
        county: 'Bihor',
        countyHistorical: 'Bihar',
        country: 'RO',
        lat: 46.66,
        lng: 22.35,
        arrival: '1910-07-03',
        departure: '1910-07-05',
        recordCount: 3,
        songIds: ['bsys-2', 'bsys-8', 'fmbc-1'],
        kmFromPrevious: 260.4,
        locationConfidence: 'resolved',
      },
      {
        seq: 2,
        placeId: 'ro/crisana/bihor/ineu',
        village: 'Ineu',
        villageHistorical: 'Köröskisjenő',
        county: 'Bihor',
        countyHistorical: 'Bihar',
        country: 'RO',
        lat: 46.43,
        lng: 21.83,
        arrival: '1910-07-08',
        departure: '1910-07-08',
        recordCount: 1,
        songIds: ['fmbc-2'],
        kmFromPrevious: 47.2,
        locationConfidence: 'resolved',
      },
    ],
    distanceKm: 307.6,
    recordCount: 4,
    facts: facts({ counties: ['Bihor'], countiesHistorical: ['Bihar'], villages: 2, ethnicGroups: { Romanian: 4 } }),
    songIds: ['bsys-2', 'bsys-8', 'fmbc-1', 'fmbc-2'],
    nowIn: ['RO'],
    romanianMaterial: null,
    derivation: { gapDays: 10, jumpKm: 250, splitReasons: ['gap'], generator: 'test' },
  },
  {
    id: 'J-1913-03-01',
    derivedFrom: 'date-gap',
    kind: 'route',
    collector: 'Bartók Béla',
    label: null,
    labelDateRaw: null,
    labelPlaceRaw: null,
    sourceUrl: null,
    countOnline: null,
    recordsOnline: true,
    dateStart: '1913-03-15',
    dateEnd: '1913-03-17',
    dateConfidence: 'day',
    datePeriods: [{ start: '1913-03-15', end: '1913-03-17', precision: 'day', qualifiers: [], raw: null, uncertain: false }],
    recordDateRange: { start: '1913-03-15', end: '1913-03-17' },
    days: 3,
    departure,
    stops: [
      {
        seq: 1,
        placeId: 'ro/crisana/bihor/beius',
        village: 'Beiuș',
        villageHistorical: 'Belényes',
        county: 'Bihor',
        countyHistorical: 'Bihar',
        country: 'RO',
        lat: 46.66,
        lng: 22.35,
        arrival: '1913-03-15',
        departure: '1913-03-15',
        recordCount: 2,
        songIds: ['gyuj-1', 'gyuj-2'],
        kmFromPrevious: 260.4,
        locationConfidence: 'resolved',
      },
      {
        seq: 2,
        placeId: 'ro/crisana/bihor/nomap',
        village: 'Tărcaia',
        villageHistorical: 'Tárkány',
        county: 'Bihor',
        countyHistorical: 'Bihar',
        country: 'RO',
        lat: null,
        lng: null,
        arrival: '1913-03-16',
        departure: '1913-03-16',
        recordCount: 1,
        songIds: ['bsys-12'],
        kmFromPrevious: null,
        locationConfidence: 'unresolved',
      },
      {
        seq: 3,
        placeId: 'ro/crisana/bihor/ineu',
        village: 'Ineu',
        villageHistorical: 'Köröskisjenő',
        county: 'Bihor',
        countyHistorical: 'Bihar',
        country: 'RO',
        lat: 46.43,
        lng: 21.83,
        arrival: '1913-03-17',
        departure: '1913-03-17',
        recordCount: 1,
        songIds: ['rfm-3'],
        kmFromPrevious: 47.2,
        locationConfidence: 'resolved',
      },
    ],
    distanceKm: 307.6,
    recordCount: 4,
    facts: facts({ counties: ['Bihor'], countiesHistorical: ['Bihar'], villages: 3 }),
    songIds: ['bsys-12', 'gyuj-1', 'gyuj-2', 'rfm-3'],
    nowIn: ['RO'],
    romanianMaterial: null,
    derivation: { gapDays: 10, jumpKm: 250, splitReasons: ['gap'], generator: 'test' },
  },
  {
    id: 'J-1918-05-01',
    derivedFrom: 'date-gap',
    kind: 'route',
    collector: 'Bartók Béla',
    label: null,
    labelDateRaw: null,
    labelPlaceRaw: null,
    sourceUrl: null,
    countOnline: null,
    recordsOnline: true,
    dateStart: '1918-05-18',
    dateEnd: '1918-05-18',
    dateConfidence: 'day',
    datePeriods: [{ start: '1918-05-18', end: '1918-05-18', precision: 'day', qualifiers: [], raw: null, uncertain: false }],
    recordDateRange: { start: '1918-05-18', end: '1918-05-18' },
    days: 1,
    departure,
    stops: [
      {
        seq: 1,
        placeId: 'hu/unresolved/ujszasz',
        village: null,
        villageHistorical: 'Újszász',
        county: null,
        countyHistorical: 'Pest-Pilis-Solt-Kiskun',
        country: 'HU',
        lat: null,
        lng: null,
        arrival: '1918-05-18',
        departure: '1918-05-18',
        recordCount: 1,
        songIds: ['bsys-26'],
        kmFromPrevious: null,
        locationConfidence: 'unresolved',
      },
    ],
    distanceKm: null,
    recordCount: 1,
    facts: facts({ countiesHistorical: ['Pest-Pilis-Solt-Kiskun'], villages: 1 }),
    songIds: ['bsys-26'],
    nowIn: ['HU'],
    romanianMaterial: null,
    derivation: { gapDays: 10, jumpKm: 250, splitReasons: ['gap'], generator: 'test' },
  },
]

const village = (id: string, over: Record<string, unknown>) =>
  ({
    id,
    status: 'existing',
    name: null,
    nameHistorical: null,
    qid: null,
    wikidataUrl: null,
    coord: null,
    county: null,
    countyHistorical: null,
    names: { ro: null, hu: null, en: null, native: [], historical: [] },
    admin: { commune: null, county: null, countyRo: null },
    dissolved: null,
    inception: null,
    replacedBy: null,
    population: null,
    evidence: [],
    ...over,
  }) as VillagesFile['villages'][string]

export const fixtureVillages: VillagesFile = {
  _meta: { attribution: 'Village names, coordinates, administrative units and status: Wikidata contributors (CC0)' },
  villages: {
    'ro/crisana/bihor/beius': village('ro/crisana/bihor/beius', {
      status: 'existing',
      name: 'Beiuș',
      nameHistorical: 'Belényes',
      qid: 'Q1',
      wikidataUrl: 'https://www.wikidata.org/wiki/Q1',
      county: 'Bihor',
      countyHistorical: 'Bihar',
      names: { ro: 'Beiuș', hu: 'Belényes', en: 'Beiuș', native: [], historical: [] },
      evidence: ['Q1 score 9: county Bihor County; 0.4 km from gazetteer coordinate'],
    }),
    'ro/crisana/bihor/ineu': village('ro/crisana/bihor/ineu', {
      status: 'renamed',
      name: 'Ineu',
      nameHistorical: 'Köröskisjenő',
      qid: 'Q2',
      wikidataUrl: 'https://www.wikidata.org/wiki/Q2',
      county: 'Bihor',
      countyHistorical: 'Bihar',
      names: { ro: 'Ineu', hu: 'Köröskisjenő', en: 'Ineu', native: [], historical: [{ name: 'Inău', until: '1965' }] },
      evidence: ['Q2 score 8: county Bihor County; 1.1 km from gazetteer coordinate; former name Inău until 1965'],
    }),
    'ro/crisana/bihor/nomap': village('ro/crisana/bihor/nomap', {
      status: 'unknown',
      name: 'Tărcaia',
      nameHistorical: 'Tárkány',
      county: 'Bihor',
      countyHistorical: 'Bihar',
      evidence: ['no candidate passed the confidence threshold'],
    }),
    'hu/unresolved/gyoma': village('hu/unresolved/gyoma', {
      status: 'abandoned',
      name: 'Gyoma',
      nameHistorical: 'Gyoma',
      qid: 'Q3',
      wikidataUrl: 'https://www.wikidata.org/wiki/Q3',
      dissolved: '1981-01-01',
      evidence: ['Q3 score 7: type former settlement; dissolved 1981'],
    }),
    'ro/transylvania/cluj/merged': village('ro/transylvania/cluj/merged', {
      status: 'merged',
      name: 'Nadășu',
      nameHistorical: 'Nádas',
      replacedBy: { label: 'Izvoru Crișului', qid: 'Q4' },
      evidence: ['replaced by Q4'],
    }),
  },
}

export const fixtureEvents: ContextEvent[] = [
  {
    id: '1909-bihor-collecting-begins',
    date: '1909-07',
    dateEnd: '1910-08',
    dateConfidence: 'approximate',
    kind: 'biography',
    title: 'Romanian collecting begins in Bihor county',
    summary: 'Bartok began systematic collecting of Romanian folk music in Bihor county in the summer of 1909.',
    source: { citation: 'RFM, vol. I, Introduction (Suchoff)' },
  },
  {
    id: '1913-bihor-volume',
    date: '1913',
    kind: 'publication',
    title: 'Chansons populaires roumaines du departement Bihar published',
    summary: 'The Bihor collection appeared in Bucharest in 1913.',
    source: { citation: 'Bela Bartok, Chansons populaires roumaines du departement Bihar (Bucharest: Academia Romana, 1913)', url: 'https://example.org/bihar-1913' },
  },
  {
    id: '1914-war',
    date: '1914-07-28',
    dateEnd: '1918-11-11',
    kind: 'border',
    title: 'First World War: fieldwork curtailed',
    summary: 'The war ended most of the collecting.',
    source: { citation: "Bela Bartok, 'Autobiography' (1921), in Essays" },
  },
  {
    id: '1920-trianon',
    date: '1920-06-04',
    kind: 'border',
    title: 'Treaty of Trianon signed',
    summary: 'Transylvania, the Banat and the eastern Partium passed to Romania.',
    source: { citation: 'Treaty of Peace, Trianon, 4 June 1920', url: 'https://en.wikisource.org/wiki/Treaty_of_Trianon' },
  },
  {
    id: 'uncited',
    date: '1913-05',
    kind: 'statement',
    title: 'Uncited entry that must never render',
    summary: 'x',
  },
]

export const fixtureBorders = {
  type: 'FeatureCollection',
  meta: {
    year: 1910,
    sources: [{ id: 'test-src', title: 'Test borders', url: 'https://example.org', licence: 'CC0', attribution: 'Test borders: example.org (CC0)' }],
  },
  features: [],
}
