from common import mek, kel, src, stop

ENTRIES = [
 {
  "id": "cur-1914-01-01", "matchesCollection": "85", "alsoMatchesCollections": [],
  "title": "Hont county, January 23-27, 1914: Teszer, Egyhazmarot, Lisso, Berencsfalu, Bakabanya",
  "dateStart": "1914-01-23", "dateEnd": "1914-01-27", "datePrecision": "day",
  "departure": {"place": "Budapest via Ipolysag", "evidence": "documented"},
  "stops": [stop("Teszer", "Hontianske Tesare, Slovakia", "Krupina district", "1914-01-23", "1914-01-23", "First stop after Ipolysag.", country="SK"), stop("Egyhazmarot", "Hontianske Moravce, Slovakia", "Krupina district", "1914-01-23", "1914-01-27", "Base (pastor Bobal).", country="SK"), stop("Lisso", "Lisov, Slovakia", "Krupina district", "1914-01", "1914-01", "Collects there or from singers from there.", country="SK"), stop("Berencsfalu", "Prencov, Slovakia", "Banska Stiavnica district", "1914-01", "1914-01", "Songs from singers of Berencsfalu.", country="SK", confidence="inferred"), stop("Bakabanya", "Pukanec, Slovakia", "Levice district", "1914-01", "1914-01", "Songs from singers of Bakabanya.", country="SK", confidence="inferred")],
  "return": {"place": "Rakoskeresztur via Ipolysag", "date": "1914-01-27", "evidence": "documented"},
  "companions": ["Samuel Bobal"], "romanianMaterial": False,
  "summary": "On 23 January 1914 Bartok travelled via Ipolysag to Teszer and Egyhazmarot in Hont county and collected there and at Lisso, and from singers of Berencsfalu and Bakabanya, returning on 27 January.",
  "sources": [mek(139, "Januar 23-an Budapestrol Ipolysagon keresztul Teszerre, illetve Egyhazmarotra utazik; ott es Lisson, valamint Berencsfaluban es Bakabanyan, vagy onnan szarmazo enekesektol gyujt. Januar 27-en Ipolysagon keresztul hazater"), src("GYUJ", "entry 85")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1914-02-01", "matchesCollection": "86", "alsoMatchesCollections": [],
  "title": "Bihar county, from February 21, 1914: Havasdombro monograph village and Belenyesorvenyes",
  "dateStart": "1914-02-21", "dateEnd": "1914-02-28", "datePrecision": "phrase",
  "departure": {"place": "Rakoskeresztur (announced to Busitia February 13)", "evidence": "documented"},
  "stops": [stop("Belenyesorvenyes", "Urvis de Beius", "Bihor", "1914-02", "1914-02", "Lodged with the forester Isaias Marele, who organised a 'kalaka' at which singers from Havasdombro and nearby villages (Borz, Pantasa, Solyom, Tenkeszeplak) performed; the songs of those villages were therefore recorded here (Kelemen, with cylinder numbers MF 3520-3523)."), stop("Havasdombro", "Dumbravita de Codru", "Bihor", "1914-02", "1914-02", "Village chosen for a complete folk-music monograph; visited with Busitia for the Sunday dance; about 40 dance tunes from the old fiddler Petrisor Pusco; alphorn recordings; nearly 70 melodies."), stop("Biharkaba", "Cabesti", "Bihor", "1914-02", "1914-02", "Chronology: songs 'eredo' from Biharkaba.", confidence="inferred"), stop("Solyom", "Soimi", "Bihor", "1914-02", "1914-02", "Singers came to Orvenyes (Kelemen); RFM IV: Soimi, Ion Mot (45), II. 1914.", confidence="inferred"), stop("Pocsafalva", "Pocioveliste", "Bihor", "1914-02", "1914-02", "Chronology: songs from Pocsafalva.", confidence="inferred"), stop("Ciganyfalva (Pantasa)", "Pantasesti", "Bihor", "1914-02", "1914-02", "Kelemen: Pantasa, singers came to Orvenyes.", confidence="inferred"), stop("Tenkeszeplak", "Suplacu de Tinca", "Bihor", "1914-02", "1914-02", "Singers came to Orvenyes (Kelemen).", confidence="inferred"), stop("Borz", "Borz", "Bihor", "1914-02", "1914-02", "Ana Ardelean of Borz sang at Orvenyes; Kelemen corrects RFM's 'IV. 1914' for Borz to February 1914.", confidence="inferred")],
  "return": {"place": "Rakoskeresztur (letter from there March 10)", "date": "1914-02-28", "evidence": "inferred", "note": "End of the trip not dated; part of the cylinders were left at Belenyes for a later Havasdombro visit."},
  "companions": ["Ioan Busitia (found the village, accompanied him to Havasdombro)", "Isaias Marele, forester at Belenyesorvenyes (host)"],
  "romanianMaterial": True,
  "summary": "On 21 February 1914 Bartok went to Bihar county to survey the complete folk music of one village, Havasdombro, for a planned monograph; because the village priest declined to guide him he lodged with the forester Isaias Marele at neighbouring Belenyesorvenyes, where a gathering brought singers from Havasdombro, Borz, Pantasa, Solyom and Tenkeszeplak. With Busitia he attended the Sunday dance at Havasdombro and notated about forty dance tunes from the old fiddler Petrisor Pusco and alphorn signals. Kelemen shows from the cylinder numbers that the Borz songs dated April 1914 in RFM belong to this February trip.",
  "sources": [mek(139, "Februar 13-an Busitia Janosnak irja Belenyesre, hogy 21-en ujabb bihari gyujtesre keszul ... Februar 21-en Biharba utazik, ahol Biharkaba, Havasdombro, Solyom, Belenyesorvenyes, Pocsafalva, Ciganyfalva es Tenkeszeplak kozsegbol eredo dalokat gyujt."), kel(403, "A bihari ut celja ez alkalommal az volt, hogy egy adott falu - Havasdombro - teljes nepzenei anyagat felmerje egy kesobbi monografia szamara. ... Bartok a kozeli Orvenyesen egy Marele Isaias nevu erdesz hazanal szallt meg ... Marele erdesz nagy 'kalakat' rendezett. ... Havasdombrora Busitia kisereteben ment ... Petrisor Pusco-tol mintegy 40 tancdallamot jegyzett le. ... Kozel 70 dallam"), kel(411, "note 16: A helyes idopont: 1914 februar. Ekkor kerult sor az orvenyesi es a havasdombroi gyujtoutra. Ana Ardelean, a Borz kozsegbe valo parasztlany a szomszedos orvenyesen, Marele erdesz hazaban enekelte fonografba dalait ... MF 3520-3523"), kel(407, "locality list, Bihar: Cabesti 1914. II.; Dumbravita-de-Codru 1914. II., 1917. VII.; Pantasesti, Pocioveliste 1914. II.; Soimi 1914. II.; Suplacul-de-Tinca 1914. II.; Urvis 1914. II., 1917. VII."), src("GYUJ", "entry 86")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1914-03-01", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Cserbel musicians in Budapest, March 18, 1914 (lecture 'A hunyadi roman nep zenedialektusa')",
  "dateStart": "1914-03-18", "dateEnd": "1914-03-18", "datePrecision": "day",
  "departure": {"place": "Budapest (Hungarian Ethnographic Society)", "evidence": "documented"},
  "stops": [stop("Budapest", "Budapest, Hungary", "Budapest", "1914-03-18", "1914-03-18", "Not a field trip: two musicians (bagpipe and flute) and two women singers from Cserbel (Cerbal, Hunyad county) performed at Bartok's lecture; they were guests at Rakoskeresztur.", country="HU")],
  "return": None, "companions": [], "romanianMaterial": True,
  "summary": "For his lecture to the Hungarian Ethnographic Society on 18 March 1914 Bartok brought two musicians and two singers from Cserbel, one of the most isolated villages of his Hunyad trip, to Budapest to perform in person; the lecture appeared in Ethnographia as 'A hunyadi roman nep zenedialektusa'. Included because any Cserbel records dated March 1914 were made in Budapest, not in the village.",
  "sources": [mek(139, "az egyik legelzartabb kozsegbol, Cserbelbol 2 zeneszt (dudast es furulyast) es 2 asszonyenekest akar felhozni Budapestre"), mek(140, "Marcius 18-an megtartja eloadasat A hunyadi roman nep zenedialektusa cimmel. A szereploket Bartokek vendegul latjak rakoskereszturi lakasukon"), src("IRASAI-HUNYAD", "Ethnographia XXV/2 (March 1914), 108-115")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1914-04-01", "matchesCollection": "87", "alsoMatchesCollections": ["88", "89", "90"],
  "title": "Maros-Torda county (upper Maros, Gorgeny and Nyarad valleys), April 3-21, 1914, with Marta Ziegler collecting separately",
  "dateStart": "1914-04-03", "dateEnd": "1914-04-21", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur to Marosvasarhely, April 3 (with his wife; lodging with Dr Karoly Ziegler)", "evidence": "documented"},
  "stops": [stop("Marosvasarhely", "Targu Mures", "Mures", "1914-04-03", "1914-04-03", "Base; husband and wife set out on separate collecting routes."), stop("Disznajo", "Valenii de Mures", "Mures", "1914-04-04", "1914-04-05", "14 cylinders on April 4; letter to his wife on the 5th describing the melody types."), stop("Marosliget", "Dumbrava (Vatava)", "Mures", "1914-04-06", "1914-04-06", "April 6."), stop("Marosvecs", "Brancovenesti", "Mures", "1914-04-06", "1914-04-06", "April 6."), stop("Felsorepa", "Vatava", "Mures", "1914-04-07", "1914-04-07", "April 7; postcard to Busitia posted at Gorgenyszentimre."), stop("Gorgenyszentimre", "Gurghiu", "Mures", "1914-04-07", "1914-04-07", "Postcard posted here."), stop("Idecspataka", "Idicel", "Mures", "1914-04-07", "1914-04-08", "Route Idecspataka - Libanfalva - Gorgenyhodak."), stop("Libanfalva", "Ibanesti", "Mures", "1914-04-08", "1914-04-08", "On the route."), stop("Gorgenyhodak", "Hodac", "Mures", "1914-04-08", "1914-04-09", "On the route."), stop("Gorgenyorsova", "Orsova", "Mures", "1914-04-09", "1914-04-09", "April 9, then in heavy rain to Kincses."), stop("Kincses", "Chincis", "Mures", "1914-04-09", "1914-04-11", "April 9-11."), stop("Nyaradremete", "Eremitu", "Mures", "1914-04-11", "1914-04-13", "Arrives on the evening of April 11, stays several days; long letter to his wife April 12-13 (Easter). Index 88: April 11-13, 40 records."), stop("Nyaradkoszvenyes", "Matrici", "Mures", "1914-04-14", "1914-04-14", "April 14. Index 89: 29 records."), stop("Jobbagytelke", "Sambrias", "Mures", "1914-04-15", "1914-04-15", "April 15."), stop("Gorgenyorsova", "Orsova", "Mures", "1914-04-16", "1914-04-16", "April 16 route Gorgenyorsova - Kincsesfo - Felsooroszi - Nyaradremete."), stop("Kincsesfo", "Comori", "Mures", "1914-04-16", "1914-04-16", "On the April 16 route."), stop("Felsooroszi", "Urisiu de Sus", "Mures", "1914-04-16", "1914-04-16", "On the April 16 route; the colinda text later used in Cantata profana was noted here (Kelemen)."), stop("Nyaradremete", "Eremitu", "Mures", "1914-04-16", "1914-04-16", "End of the April 16 route."), stop("Bala", "Bala", "Mures", "1914-04-17", "1914-04-17", "April 17 (Kelemen attributes Bala partly to Marta's collecting)."), stop("Kortekapu", "Poarta (Curtecap)", "Mures", "1914-04-18", "1914-04-18", "April 18."), stop("Nyaradto", "Ungheni", "Mures", "1914-04", "1914-04", "Collected by Marta Ziegler (with Marosliget and Mezoszabad, and per Kelemen Bala, Kortekapu, Maroskisfalud, Mezomajos).", confidence="inferred"), stop("Mezoszabad", "Voiniceni", "Mures", "1914-04", "1914-04", "Collected by Marta Ziegler.", confidence="inferred"), stop("Maroskisfalud", "Nazna", "Mures", "1914-04", "1914-04", "Collected by Marta Ziegler (Kelemen).", confidence="inferred"), stop("Mezomajos", "Moisa", "Mures", "1914-04", "1914-04", "Collected by Marta Ziegler (Kelemen); RFM IV: Moisa, Rafila Rosca, IV. 1914, Z.", confidence="inferred")],
  "return": {"place": "Rakoskeresztur, dawn of April 21 (departure April 20)", "date": "1914-04-21", "evidence": "documented"},
  "companions": ["Marta Ziegler (his wife), who collected on her own in villages near Marosvasarhely"],
  "romanianMaterial": True,
  "summary": "On 3 April 1914 Bartok and his wife travelled to Marosvasarhely and from there collected on separate routes. His own itinerary is documented day by day: Disznajo (4-5 April), Marosliget and Marosvecs (6), Felsorepa (7), then Idecspataka, Libanfalva and Gorgenyhodak, Gorgenyorsova and Kincses (9), Nyaradremete from the evening of the 11th over Easter, Nyaradkoszvenyes (14), Jobbagytelke (15), the Gorgenyorsova-Kincsesfo-Felsooroszi-Nyaradremete round on the 16th, Bala (17) and Kortekapu (18). Marta Ziegler collected at Nyaradto, Marosliget, Mezoszabad and, according to Kelemen, Bala, Kortekapu, Maroskisfalud and Mezomajos (RFM marks her items 'Z.'). They left on 20 April and reached home at dawn on the 21st; the index splits the trip into four entries (87-90).",
  "sources": [mek(140, "Aprilis 3-an felesegevel egyutt Marosvasarhelyre utazik ... Aprilis 4-en Bartok Disznajon ... 14 hengernyi dallamot gyujt ... 6-an Marosligeten, majd Marosvecsen, 7-en Felsorepan gyujt ... Idecspataka-Libanfalva-Gorgenyhodak utvonalon. Aprilis 9-en Gorgenyorsovarol nagy esoben Kincsesre megy, 11-en este erkezik Nyaradremetere ... 14-en Nyaradkoszvenyesen, 15-en Jobbagytelken es 16-an a Gorgenyorsova-Kincsesfo-Felsooroszi-Nyaradremete utvonalon gyujt. Felesege idokozben onalloan gyujt (a Nyaradto, Nogradto [sic], Marosliget es Mezoszabadi kozsegekbol szarmazo nepdalok ...). Aprilis 17-en Bartok Bala kozsegben, 18-an Kortekapun gyujt. Aprilis 20-an hazaindul. Aprilis 21-en hajnalban erkezik"), kel(403, "Aprilisban felesegevel Ziegler Martaval egyutt Maros-Torda megyebe utaztak. ... Egy Felsooroszi nevu faluban jegyezte fel azt a kolinda-szoveget amelyet kesobb a Cantata profana-ban hasznalt fel. ... Bala, Kortekapu, Maroskisfalud, Mezomajos, Nyaradto kozsegekben, ferje utmutatasai alapjan, o vegezte a gyujtest."), kel(409, "locality list, Maros-Torda: 19 localities, 428 melodies, 1914. IV. (with Toplita, Rusii-Munti, Sacalul-de-Padure, Sangerul-de-Padure 1916. VIII.)"), src("RFM4", "source data e.g. 'Urisiu de sus (Mures-Turda), Vasile Suciu (31), IV. 1914'; 'Idicel (Mures-Turda), Susana si Rafila Oncea (43,16), IV. 1914'; 'Moisa (Mures-Turda), Rafila Rosca, IV. 1914, Z.'"), src("GYUJ", "entries 87-90")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1915-02-01", "matchesCollection": "91", "alsoMatchesCollections": [],
  "title": "Rakoskeresztur, early 1915: a few Slovak songs notated at home",
  "dateStart": "1915-01", "dateEnd": "1915-03", "datePrecision": "month",
  "departure": {"place": "none (at home)", "evidence": "documented"},
  "stops": [stop("Rakoskeresztur", "Budapest XVII (Rakoshegy), Hungary", "Budapest", "1915-01", "1915-03", "'Rakoskereszturon nehany szlovak dalt jegyez le' before the Easter trip to Zolyom.", country="HU")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "With field trips suspended by the war, Bartok notated a few Slovak songs at his home in Rakoskeresztur early in 1915 before travelling to Zolyom county at Easter. The index has 11 records for January-February 1915.",
  "sources": [mek(145, "A felbenmaradt nepdalgyujtes tovabbra sem hagyja nyugodni. Rakoskereszturon nehany szlovak dalt jegyez le, majd a husveti szunetben Zolyom megyebe utazik."), src("GYUJ", "entry 91")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1915-04-01", "matchesCollection": "92", "alsoMatchesCollections": [],
  "title": "Zolyom county, Easter 1915 (April 3-13): Hedel, Perhat, Erdokoz, Szelcse, Nagyret, Beneshaza, Erdobadony",
  "dateStart": "1915-04-03", "dateEnd": "1915-04-13", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur; letter written on the train at Fulek, April 3", "evidence": "documented"},
  "stops": [stop("Besztercebanya", "Banska Bystrica, Slovakia", "Banska Bystrica", "1915-04-03", "1915-04-04", "Arrival on the evening of April 3; base.", country="SK"), stop("Hedel", "Hiadel, Slovakia", "Banska Bystrica", "1915-04-04", "1915-04-09", "Collecting begins Easter Sunday; songs from Hedel, Perhat, Erdokoz, Szelcse, Nagyret, Beneshaza, Erdobadony and Barsbaracska.", country="SK"), stop("Zolyombrezo", "Podbrezova, Slovakia", "Brezno", "1915-04-09", "1915-04-09", "Transit April 9.", country="SK"), stop("Beneshaza", "Benus, Slovakia", "Brezno", "1915-04-09", "1915-04-12", "April 9 onwards.", country="SK")],
  "return": {"place": "Rakoskeresztur, afternoon of April 13", "date": "1915-04-13", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "In the Easter holiday of 1915 Bartok made his first wartime collecting trip, to Zolyom county: he reached Besztercebanya on the evening of 3 April, began on Easter Sunday and notated songs from Hedel, Perhat, Erdokoz, Szelcse, Nagyret, Beneshaza and Erdobadony (and from Barsbaracska), travelling on 9 April via Zolyombrezo to Beneshaza, and came home on the 13th.",
  "sources": [mek(145, "Aprilis 3-an Fulekrol ... a vonaton ir ... Este erkezik Besztercebanyara. Aprilis 4-en (Husvetvasarnap) megkezdi gyujtoutjat; Hedel, Perhat, Erdokoz, Szelcse, Nagyret, Beneshaza, Erdobadony zolyomi kozsegekbol es Barsbaracskarol eredo nepdalokat jegyez le. Aprilis 9-en Besztercebanyarol Zolyombrezon at Beneshazara utazik. Aprilis 13-an delutan erkezik haza"), src("GYUJ", "entry 92")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1915-07-01", "matchesCollection": "93", "alsoMatchesCollections": [],
  "title": "Zolyom county, July 9 - August 25, 1915: Hedel, Padkoc, Feketebalog, Ponik, Garamsalfalva",
  "dateStart": "1915-07-09", "dateEnd": "1915-08-25", "datePrecision": "day",
  "departure": {"place": "Budapest to Besztercebanya, July 9", "evidence": "documented"},
  "stops": [stop("Besztercebanya", "Banska Bystrica, Slovakia", "Banska Bystrica", "1915-07-09", "1915-07-10", "Transit.", country="SK"), stop("Hedel", "Hiadel, Slovakia", "Banska Bystrica", "1915-07-10", "1915-08-02", "Lodging with the teacher Gasparik; by July 20 '14 henger es kb. 100 lejegyzes'; family joins him August 2 for four days.", country="SK"), stop("Padkoc", "Podkonice, Slovakia", "Banska Bystrica", "1915-07-18", "1915-07-19", "'nagy es kivaloan sikerult gyujtest rendez, valoszinuleg Padkocon'; photograph of 'padkoczi kivalo oregeim'.", country="SK"), stop("Feketebalog", "Cierny Balog, Slovakia", "Brezno", "1915-07-28", "1915-07-28", "July 28.", country="SK"), stop("Besztercebanya", "Banska Bystrica, Slovakia", "Banska Bystrica", "1915-08-07", "1915-08-11", "A few days in a wooden house on an island of the Garam; begins photographing.", country="SK"), stop("Ponik", "Poniky, Slovakia", "Banska Bystrica", "1915-08-11", "1915-08-19", "Letter of August 19 from Ponik: 400 melodies notated so far; three more days in another village.", country="SK"), stop("Garamsalfalva", "Salkova, Slovakia", "Banska Bystrica", "1915-08-23", "1915-08-23", "August 23; departure on the 24th.", country="SK")],
  "return": {"place": "Rakoskeresztur", "date": "1915-08-25", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Bartok spent most of the summer of 1915 in Zolyom county: from 10 July he lodged at Hedel with the teacher Gasparik and, despite the difficulty of finding singers in wartime, notated about 100 songs by 20 July, held a large session at Padkoc (18-19 July), visited Feketebalog on 28 July, then stayed at Besztercebanya and Ponik (400 melodies by 19 August) and Garamsalfalva (23 August), returning home on the 25th. July songs come from Ponik, Perhat, Cserpatak and Erdobadony, August songs from Ponik, Mezokoz, Hedel, Perhat and Cserpatak.",
  "sources": [mek(146, "Julius 9-en Bartok Budapestrol Besztercebanyara utazik, majd 10-en tovabb Hedelre ... Julius 18-an es 19-en nagy es kivaloan sikerult gyujtest rendez, valoszinuleg Padkocon. Julius 20-an ... 'Eddig 14 henger es kb. 100 lejegyzes'. ... Julius 28-an Feketebalogon"), mek(147, "Augusztus 19-en Ponikrol irja edesanyjanak, hogy eddig 400 dallamot jegyzett le ... Augusztus 23-an Garamsalfalvan jar, majd 24-en hazaindul. Augusztus 25-en erkezik Rakoskereszturra."), src("GYUJ", "entry 93")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1915-11-01", "matchesCollection": "94", "alsoMatchesCollections": [],
  "title": "Ponik (Zolyom county), November 1915",
  "dateStart": "1915-11-18", "dateEnd": "1915-11-30", "datePrecision": "month",
  "departure": {"place": "Budapest to Besztercebanya, after a lesson on the morning of November 18", "evidence": "documented"},
  "stops": [stop("Ponik", "Poniky, Slovakia", "Banska Bystrica", "1915-11", "1915-11", "'Novemberben Bartok Ponikon (Zolyom varmegye) gyujt.'", country="SK")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "In November 1915 Bartok travelled again to Besztercebanya and collected at Ponik; only the month is recorded.",
  "sources": [mek(148, "November 16-an ... majd Besztercebanyara utazik ... Novemberben Bartok Ponikon (Zolyom varmegye) gyujt."), src("GYUJ", "entry 94")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1915-12-01", "matchesCollection": "97", "alsoMatchesCollections": ["99"],
  "title": "Zolyom county, December 26, 1915 - January 4, 1916: Feketebalog and Ponik",
  "dateStart": "1915-12-26", "dateEnd": "1916-01-04", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur", "evidence": "documented"},
  "stops": [stop("Feketebalog", "Cierny Balog, Slovakia", "Brezno", "1915-12-27", "1915-12-29", "Collects December 27-29.", country="SK"), stop("Ponik", "Poniky, Slovakia", "Banska Bystrica", "1916-01-01", "1916-01-02", "Collects January 1-2 (the index puts Ponik in 'Gomor county'; it is in Zolyom).", country="SK"), stop("Zolyom", "Zvolen, Slovakia", "Zvolen", "1916-01-04", "1916-01-04", "Postcards from Zolyom on the way home: 'talan utoljara jarok Zolyom varmegyeben'.", country="SK")],
  "return": {"place": "Rakoskeresztur", "date": "1916-01-04", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "On 26 December 1915 Bartok made his fourth Zolyom trip, collecting at Feketebalog on 27-29 December and at Ponik on 1-2 January 1916, and started home on 4 January, writing from Zolyom that he would probably suspend the work for the duration of the war (he was back at Easter).",
  "sources": [mek(149, "December 26-an Bartok negyedizben utazik Zolyom varmegyebe, ahol 27-28-29-en Feketebalogon gyujt. 1916 Januar 1-en es 2-an Ponikon gyujt. Januar 4-en hazaindul."), src("GYUJ", "entries 97, 99")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1916-04-01", "matchesCollection": "101", "alsoMatchesCollections": [],
  "title": "Zolyom county, April 22-30, 1916: Garamolaszka, Besztercebanya barracks, Cserpatak",
  "dateStart": "1916-04-22", "dateEnd": "1916-04-30", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur (Holy Saturday)", "evidence": "documented"},
  "stops": [stop("Zolyombrezo", "Podbrezova, Slovakia", "Brezno", "1916-04-22", "1916-04-22", "First stop.", country="SK"), stop("Garamolaszka", "Valaska, Slovakia", "Brezno", "1916-04-23", "1916-04-25", "Collects April 23-25.", country="SK"), stop("Besztercebanya", "Banska Bystrica, Slovakia", "Banska Bystrica", "1916-04-26", "1916-04-29", "Guest of Aladar Hubert; April 27-29 soldiers' songs in the barracks of the 16th Honved infantry regiment (songs from Zolyommiklos, Loper, Szinobanya, Dabar probably collected there).", country="SK"), stop("Zolyombrezo", "Podbrezova, Slovakia", "Brezno", "1916-04-29", "1916-04-29", "Transit.", country="SK"), stop("Cserpatak", "Cierny Potok? (Cserpatak, Zolyom)", "Banska Bystrica", "1916-04-30", "1916-04-30", "Collects April 30.", country="SK")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "Authorised in March 1916 to record soldiers' songs in barracks, Bartok went to Zolyom county on Holy Saturday, 22 April: he collected at Garamolaszka on 23-25 April, in the barracks of the 16th Honved regiment at Besztercebanya on 27-29 April, and at Cserpatak on the 30th. Further short visits to Zolyombrezo followed on 23 June and 4-6 July.",
  "sources": [mek(150, "Aprilis 22-en (Nagyszombaton) Zolyom varmegyebe utazik, eloszor Zolyombrezon, majd 23-24-25-en Garamolaszkan gyujt, azutan Besztercebanyara megy ... Aprilis 27-28-29-en a besztercebanyai 16-os honved gyalogezred laktanyajaban katonadalokat gyujt ... Aprilis 30-an Cserpatakon (Zolyom varmegye) gyujt."), src("GYUJ", "entry 101")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1916-08-01", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Marosvasarhely barracks, August 6-8, 1916: soldiers' songs (Romanian soldiers from various villages)",
  "dateStart": "1916-08-06", "dateEnd": "1916-08-08", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur to Marosvasarhely with his family, July 29 (guest of Dr Karoly Ziegler)", "evidence": "documented"},
  "stops": [stop("Marosvasarhely", "Targu Mures", "Mures", "1916-08-06", "1916-08-08", "Barracks of the 22nd Honved infantry regiment; material from Marosvasarhely, Mezokobolkut, Maroshevz, Gyulatelke, Pusztakamaras, Marosoroszfalu, Erdoszakal, Erdoszengyel, plus (Kelemen) Remetemezo and an unnamed Hunyad village, all from soldiers. Bartok's 1917 report gives August 6-9, but he wrote from Rakoskeresztur on August 9."), stop("Mezokobolkut", "Fantanita", "Bistrita-Nasaud", "1916-08", "1916-08", "Soldier's home village, not visited.", confidence="inferred"), stop("Gyulatelke", "Coasta", "Cluj", "1916-08", "1916-08", "Soldier's home village, not visited.", confidence="inferred"), stop("Pusztakamaras", "Camarasu", "Cluj", "1916-08", "1916-08", "Soldier's home village, not visited.", confidence="inferred"), stop("Maroshevz", "Toplita", "Harghita", "1916-08", "1916-08", "Soldier's home village, not visited. RFM IV: 'Toplita (Mures-Torda), Vasile Voda (30), VIII. 1916'.", confidence="inferred"), stop("Marosoroszfalu", "Rusii-Munti", "Mures", "1916-08", "1916-08", "Soldier's home village, not visited.", confidence="inferred"), stop("Erdoszakal", "Sacalu de Padure", "Mures", "1916-08", "1916-08", "Soldier's home village, not visited.", confidence="inferred"), stop("Erdoszengyel", "Sangeru de Padure", "Mures", "1916-08", "1916-08", "Soldier's home village, not visited.", confidence="inferred"), stop("Remetemezo", "Pomi", "Satu Mare", "1916-08", "1916-08", "Kelemen: Pom (Satmar), Gheorghe Boca (18), IV. 1916 in RFM IV; soldier, not visited.", confidence="inferred")],
  "return": {"place": "Rakoskeresztur (letter from there August 9); wife and son stayed in Marosvasarhely until the Romanian invasion", "date": "1916-08-09", "evidence": "documented"},
  "companions": [], "romanianMaterial": True,
  "summary": "While staying with his wife's family in Marosvasarhely in the summer of 1916, Bartok collected soldiers' songs in the barracks of the 22nd Honved regiment on 6-8 August; the Romanian melodies from Mezokobolkut, Gyulatelke, Pusztakamaras, Maroshevz, Marosoroszfalu, Erdoszakal, Erdoszengyel and Remetemezo dated 1916 come from soldiers and the villages were not visited. Kelemen counts these as the only Romanian collecting of 1916. The index has no entry.",
  "sources": [mek(151, "Augusztus 6-8. kozott a marosvasarhelyi 22-es honved gyalogezred laktanyajaban folytatja a katonadalok gyujteset. Az ebbol az idoszakbol szarmazo Marosvasarhely, Mezokobolkut, Maroshevz, Gyulatelke, Pusztakamaras, Marosoroszfalu, Erdoszakal es Erdoszengyel kozsegekbol szarmazo anyag felteheto[leg] mind ebbol a gyujtesbol valo."), kel(404, "1916 nyaran, valoszinuleg marosvasarhelyi tartozkodasa idejen, kulonbozo videkre valo roman katonaktol jegyez le dallamokat"), kel(414, "note 23: Gyulatelke, Mezokobolkut, Pusztakamaras (Kolozs megye); Erdoszakal, Erdoszengyel, Maroshevz, Marosoroszfalva (Maros-Torda megye), Remetemezo (Szatmar megye), tovabba egy ismeretlen nevu Hunyad megyei falu")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1916-08-02", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Zolyom county, August 16-23, 1916: Libetbanya and Zolyombrezo",
  "dateStart": "1916-08-16", "dateEnd": "1916-08-23", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur", "evidence": "inferred"},
  "stops": [stop("Libetbanya", "Lubietova, Slovakia", "Banska Bystrica", "1916-08-16", "1916-08-23", "Visited.", country="SK"), stop("Zolyombrezo", "Podbrezova, Slovakia", "Brezno", "1916-08-16", "1916-08-23", "Visited.", country="SK")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "Between 16 and 23 August 1916 Bartok was again in Zolyom county, at Libetbanya and Zolyombrezo. Not in the index.",
  "sources": [mek(151, "Augusztus 16. es 23. kozott megint Zolyom varmegyeben (Libetbanyan es Zolyombrezon) jar.")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1917-07-01", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Arad county, July 7-16, 1917, with Egisto Tango: Soborsin and the Arad barracks",
  "dateStart": "1917-07-07", "dateEnd": "1917-07-16", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur / Budapest", "evidence": "documented"},
  "stops": [stop("Soborsin", "Savarsin", "Arad", "1917-07-07", "1917-07-08", "July 8: 'a gyujtes ... a korulmenyekhez kepest eleg jol sikerult'. RFM IV: Savarsin, Sofia Goian, VII. 1917."), stop("Arad", "Arad", "Arad", "1917-07-09", "1917-07-15", "Hotel; collects in the barrack camp of the 33rd infantry regiment: 116 Hungarian, 36 Slovak and 53 Romanian songs, 'alig eri meg a koltseget'. Songs from Monyoro, Mikelaka, Menyhaza, Marospetres, Szekudvar, Tok, Torjas, Pernyefalva and Arad partly from the field, partly from the barracks."), stop("Soborsin", "Savarsin", "Arad", "1917-07-11", "1917-07-15", "Again on July 11; on the 14th and 15th continues despite a feverish sore throat. Kelemen: Petris (Marospetres), Toc (Tok), Troias (Torjas) VII. 1917; Valea Mare (Krasso-Szoreny, near Soborsin) VII. 1917."), stop("Marospetres", "Petris", "Arad", "1917-07", "1917-07", "RFM IV: Petris (Arad), Petru Olar (30), VII. 1917.", confidence="inferred"), stop("Tok", "Toc", "Arad", "1917-07", "1917-07", "RFM IV: Toc (Arad), Joachim Luntras (41), VII. 1917.", confidence="inferred"), stop("Torjas", "Troas", "Arad", "1917-07", "1917-07", "RFM IV: Traias (Arad), Pavel Oprea (17), Gligor Halmagean (17), VII. 1917.", confidence="inferred"), stop("Marosnagyvolgy", "Valea Mare (Savarsin)", "Arad", "1917-07", "1917-07", "Kelemen note 69: the Valea Mare of the Maros district near Soborsin.", confidence="inferred")],
  "return": {"place": "Doboz (his sister's), July 16, then on to Bihar", "date": "1917-07-16", "evidence": "documented"},
  "companions": ["Egisto Tango, conductor of the Budapest Opera (who had just conducted The Wooden Prince)"],
  "romanianMaterial": True,
  "summary": "On 7 July 1917 Bartok travelled with the conductor Egisto Tango to Soborsin in Arad county, where collecting went 'fairly well under the circumstances'; from 9 July they stayed in Arad, where Bartok recorded 116 Hungarian, 36 Slovak and 53 Romanian songs in the barrack camp of the 33rd regiment, and he returned to Soborsin on 11 and 14-15 July despite illness. Romanian songs of this trip come from Soborsin, Marospetres, Tok, Torjas, Pernyefalva, Monyoro, Mikelaka, Menyhaza, Szekudvar and Arad, partly from soldiers. On 16 July they went on to his sister at Doboz. Not in the index.",
  "sources": [mek(158, "Julius 7-en Tango Egistoval Soborsinba (Arad varmegye) utazik. Julius 8-an itt 'a gyujtes ... a korulmenyekhez kepest eleg jol sikerult'. Julius 9-en Tangoval Aradra mennek ... Bartok az aradi 33-as gyalogezred barakk-taboraban gyujt, 116 magyar, 36 szlovak es 53 roman dalt ... Julius 11-en megint Soborsinban jar; 14-en es 15-en lazas torokfajassal, de folytatja a gyujtest. Julius 16-an Tangoval Aradrol Dobozra utazik ... Monyoro, Mikelaka, Menyhaza, Marospetres, Soborsin, Szekudvar, Tok, Torjas, Pernyefalva kozsegekbol es Arad varosabol"), kel(404, "1917 juliusaban tobb Arad megyei kozsegben jart, majd ezt kovetoen nemsokara ismet elindult, a szamara oly kedves bihari videkre. ... magaval vitte Tango Egisto-t"), kel(407, "locality list, Arad: 10 localities, 125 melodies, 1917. VII."), src("RFM4", "source data e.g. 'Savarsin (Arad), Sofia Goian, VII. 1917'; 'Petris (Arad), Petru Olar (30), VII. 1917'; 'Toc (Arad), Joachim Luntras (41), VII. 1917'")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1917-07-02", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Bihar county, July 20-31, 1917: Belenyesorvenyes and Havasdombro (last Romanian collecting trip)",
  "dateStart": "1917-07-20", "dateEnd": "1917-07-31", "datePrecision": "day",
  "departure": {"place": "Doboz via Nagyvarad, July 20", "evidence": "documented"},
  "stops": [stop("Nagyvarad", "Oradea", "Bihor", "1917-07-20", "1917-07-20", "Meets a former pupil; lunch with cousins."), stop("Belenyesorvenyes", "Urvis de Beius", "Bihor", "1917-07-20", "1917-07-31", "Lodging with the forester Isaias Marele; Tango falls ill on the 21st (malaria); letters from here July 24 and 28. Kelemen: only Havasdombro and Orvenyes were visited for collecting, probably by Bartok alone; RFM has 7 melodies dated VII. 1917 from the two villages."), stop("Belenyes", "Beius", "Bihor", "1917-07-22", "1917-07-24", "July 22 to Belenyes with Tango for a medical examination; Bartok returns to Orvenyes for the luggage on the 23rd and back to Belenyes on the 24th."), stop("Havasdombro", "Dumbravita de Codru", "Bihor", "1917-07", "1917-07", "Kelemen: Dumbravita-de-Codru 1914. II., 1917. VII.")],
  "return": {"place": "Rakoskeresztur via Nagyvarad, July 31 (Tango to Budapest)", "date": "1917-07-31", "evidence": "documented"},
  "companions": ["Egisto Tango (fell ill with malaria)"],
  "romanianMaterial": True,
  "summary": "From Doboz Bartok and Tango travelled on 20 July 1917 via Nagyvarad to Belenyesorvenyes, lodging again with the forester Marele; Tango fell ill on the 21st and was examined at Belenyes, and on the 28th Bartok wrote that Tango had malaria and they would return. Kelemen identifies this as Bartok's last Romanian collecting trip, with only Havasdombro and Orvenyes visited and seven melodies dated July 1917 in RFM, and rejects the earlier figure of two thousand melodies. They left via Nagyvarad on 31 July. Not in the index.",
  "sources": [mek(159, "Julius 20-an Dobozrol Nagyvaradon at Belenyesorvenyesre (Bihar varmegye) utaznak, ahol Marele Izsias erdesznel szallnak meg. ... Julius 21-en Tango megbetegszik ... Julius 22-en Belenyesre utaznak Tangoval, orvosi vizsgalatra. ... Julius 28-an ujbol Belenyesorvenyesrol ir felesegenek: Tangonak malariaja van, ezert visszautaznak. ... Julius 31-en Nagyvaradon at hazautaznak"), kel(405, "Ma mar tudjuk, hogy gyujtesi celbol csak Havasdombron es Orvenyesen jartak. Valoszinu azonban, hogy csak Bartok, mivel Tango idokozben megbetegedett. ... Az RFM koteteiben mindossze 7 dallamot talalunk a ket falubol 1917 juliusi gyujtesi datummal. Ez volt tehat Bartok utolso roman nepzenegyujto utja"), kel(407, "locality list, Bihar: Dumbravita-de-Codru 1914. II., 1917. VII.; Urvis 1914. II., 1917. VII.")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1917-12-01", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Veszto-Kertmeg puszta, Christmas 1917: a few songs",
  "dateStart": "1917-12-24", "dateEnd": "1917-12-31", "datePrecision": "phrase",
  "departure": {"place": "Rakoskeresztur, with his family", "evidence": "documented"},
  "stops": [stop("Veszto-Kertmeg puszta", "Veszto, Hungary", "Bekes", "1917-12-24", "1917-12-31", "At his sister's new post; a few songs, one labelled Sarkad (Bihar) but sung by Zsuzsa Szucs at Kertmeg.", country="HU")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "At Christmas 1917 Bartok and his family went to Kertmeg puszta near Veszto, where his sister's husband had been transferred; he collected a few songs there, including one labelled Sarkad whose singer was at Kertmeg. Not in the index.",
  "sources": [mek(161, "Karacsonykor Veszto-Kertmeg pusztara utazik csaladjaval ... Itt mindjart gyujt nehany nepdalt, melyek kozott van sarkadi (Bihar varmegye) megjelolesu is, de az adatkozlo, Szucs Zsuzsa, Kertmegen volt.")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1918-07-01", "matchesCollection": "104", "alsoMatchesCollections": [],
  "title": "Veszto-Kertmeg puszta, July 1918: 90 songs from harvest girls",
  "dateStart": "1918-07-05", "dateEnd": "1918-07-18", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur, early July", "evidence": "documented"},
  "stops": [stop("Veszto-Kertmeg puszta", "Veszto, Hungary", "Bekes", "1918-07-05", "1918-07-18", "July 10-14: 90 folk songs from harvest girls, 25 new melodies, many soldiers' songs; leaves for Belenyes on the 18th.", country="HU")],
  "return": {"place": "continues to Belenyes (separate entry)", "date": "1918-07-18", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "In early July 1918 Bartok went to his sister at Kertmeg puszta (Veszto) to put on weight; between 10 and 14 July he collected 90 songs from harvest girls, including 25 new melodies and many soldiers' songs. On 18 July he left for Belenyes. The index's '07. 1918, Veszto (31)' corresponds to this stay.",
  "sources": [mek(164, "Julius elejen Szovata helyett Kertmeg pusztara utazik hugahoz hizokurara. ... Julius 10-14. kozott aratolanyoktol 90 nepdalt gyujt, kozottuk 25 uj dallamot es sok katonanotat. ... 20-an keszul Belenyesre, de Busitia keresere mar 18-an elindul."), src("GYUJ", "entry 104")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1918-07-02", "matchesCollection": None, "alsoMatchesCollections": [],
  "title": "Belenyes and the Ponor mountains (Bihar / Kolozs counties), July 19 - about August 7, 1918",
  "dateStart": "1918-07-19", "dateEnd": "1918-08-07", "datePrecision": "phrase",
  "departure": {"place": "Kertmeg puszta (Veszto), July 18", "evidence": "documented"},
  "stops": [stop("Belenyes", "Beius", "Bihor", "1918-07-19", "1918-07-23", "With the Busitias; the Kodalys pass through on July 21 on their way to Biharfured, where Bartok visits them."), stop("Biharfured", "Stana de Vale", "Bihor", "1918-07-22", "1918-07-22", "Visit to the Kodalys.", confidence="inferred"), stop("Ponor (u.p. Jozsikafalva)", "Ponor (Belis)", "Cluj", "1918-07-24", "1918-08-07", "On horseback with Busitia into the mountains; 'Gyujtoutjuk kb. 2 hetig tart' (chronology). Kelemen: in the summer of 1918 Bartok went to the Belenyes area to rest and no collecting is known; the last Romanian collecting date in RFM is July 1917.", confidence="inferred")],
  "return": {"place": "Rakoskeresztur (at Godollo August 8)", "date": "1918-08-07", "evidence": "inferred"},
  "companions": ["Ioan Busitia"],
  "romanianMaterial": None,
  "summary": "Bartok reached Belenyes on 19 July 1918 and on the evening of 23 or 24 July rode with Busitia into the mountains towards Ponor near Jozsikafalva in Kolozs county, on a trip the chronology calls a collecting trip of about two weeks. Kelemen, however, states that the 1918 Belenyes stay was for rest and that no Romanian material of 1918 is known (Bartok's own 1930 letter to Beu dated the end of his Romanian collecting to the summer of 1918). Not in the index; included with the conflict noted.",
  "sources": [mek(164, "Julius 19-en erkezik Belenyesre ... Julius 23-an Bartok Belenyesrol irja felesegenek ... este vegre elindulnak a havasra. Lohaton mennek Busitiaval ... Uticeljuk a Kolozs varmegyei Ponor (u. p. Jozsikafalva). - Gyujtoutjuk kb. 2 hetig tart."), kel(399, "1918. nyaran Bartok csakugyan jart Belenyesen es kornyeken. Ez alkalommal azonban pihenni ment oda. Arrol, hogy meg gyujtomunkat is vegzett volna, nincsen tudomasunk.")],
  "evidenceQuality": "dates only (conflicting)",
 },
 {
  "id": "cur-1918-08-01", "matchesCollection": "100", "alsoMatchesCollections": [],
  "title": "Felsoszaszberek puszta (Besenyszog, Jasz-Nagykun-Szolnok county), August 15-26, 1918: last collecting trip in Hungary",
  "dateStart": "1918-08-15", "dateEnd": "1918-08-26", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur", "evidence": "documented"},
  "stops": [stop("Felsoszaszberek puszta (Besenyszog)", "Szaszberek, Hungary", "Jasz-Nagykun-Szolnok", "1918-08-15", "1918-08-26", "Guest of Baron Adolf Kohner; collects from the estate staff and from Slovak harvest workers; one song from Kisules (Bars county) probably notated here. 195 records online.", country="HU")],
  "return": {"place": "Rakoskeresztur via Ujszasz", "date": "1918-08-26", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "On 15 August 1918 Bartok left for what the chronology calls his last folk-song collecting trip in Hungary, to Felsoszaszberek puszta near Besenyszog as guest of Baron Adolf Kohner; he collected with good results from the estate staff and Slovak harvesters and finished on 26 August, returning via Ujszasz. In September he harmonised seven songs of the summer, among them Roza Okros's 'Angoli Borbala'.",
  "sources": [mek(165, "Augusztus 15-en indul utolso magyarorszagi nepdalgyujto utjara, a ... Felsoszaszberek pusztara (Jasz-Nagykun-Szolnok varmegye), ahol baro Kohner Adolf nagybirtokos latja vendegul. ... Augusztus 26-an befejezi gyujteset es Ujszaszon at hazaindul."), src("GYUJ", "entry 100")],
  "evidenceQuality": "documented itinerary",
 },
]
