from common import mek, kel, src, stop

BP = {"place": "Budapest", "evidence": "assumed"}
RK = {"place": "Rakoskeresztur (Rakoshegy), Bartok's home from May 1911", "evidence": "assumed"}

ENTRIES = [
 {
  "id": "cur-1904-05-01", "matchesCollection": "1", "alsoMatchesCollections": [],
  "title": "Gerlice puszta (Gomor county): summer stay, first notated folk song (from Lidi Dosa of Kibed)",
  "dateStart": "1904-05-11", "dateEnd": "1904-11-08", "datePrecision": "day",
  "departure": {"place": "Pozsony (Bratislava), via Budapest and Tornalja by rail, then by cart", "evidence": "documented"},
  "stops": [stop("Gerlice puszta (Ratko)", "Gerlica (Ratkova), Slovakia", "Revuca district", "1904-05-11", "1904-11-08", "Summer residence with the Fischer family; not a collecting trip. Around late July to mid-August absent in Bayreuth. The singer Lidi Dosa came from Kibed (Maros-Torda); Kibed was not visited.", country="SK")],
  "return": {"place": "Pozsony via Budapest", "date": "1904-11-08", "evidence": "documented"},
  "companions": [],
  "romanianMaterial": False,
  "summary": "Bartok spent the summer and autumn of 1904 at Gerlice puszta in Gomor county as the guest of the Fischer family, working on the Rhapsody op. 1. There he heard a Fischer employee, Lidi Dosa from Kibed in Maros-Torda county, sing and notated one of her songs; the chronology dates the beginning of his folk-song collecting from this. The index entry 'Gerlicepuszta / Kibed' therefore combines the place of notation with the singer's home village.",
  "sources": [mek(69, "Majus 11. korul Budapest-Tornalja utvonalon ... Gerlicere. ... Dosa Lidivel ... egy dalat lejegyzi. ... Innen szamithatjuk Bartok nepdalgyujto munkajanak kezdetet."), mek(70, "November 7-en vagy 8-an Gerlice pusztarol Budapesten at Pozsonyba utazik."), src("GYUJ", "entry 1: 'July - November, 1904. Gerlicepuszta / Kibed (8)'")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1905-06-01", "matchesCollection": "4", "alsoMatchesCollections": [],
  "title": "Veszto, Szilad puszta (Bekes county): songs collected while staying with his sister",
  "dateStart": "1905-06-08", "dateEnd": "1905-07-28", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Veszto-Szilad puszta", "Veszto, Hungary", "Bekes", "1905-06-08", "1905-07-28", "Stay at the Wenckheim estate where his brother-in-law Emil Olah Toth was steward; 'Bela ... bogarakat es magyar dalokat gyujt' (his sister, June 21).", country="HU")],
  "return": {"place": "Budapest via Bekes and Bekescsaba", "date": "1905-07-28", "evidence": "documented"},
  "companions": [],
  "romanianMaterial": False,
  "summary": "In June and July 1905 Bartok stayed with his sister at Szilad puszta near Veszto. A letter of his sister of 21 June reports that he was collecting insects and Hungarian songs; the index lists five records for the trip.",
  "sources": [mek(76, "Junius 8-an hugahoz keszul Veszto-Szilad pusztara. ... Toth Emilne azt irja edesanyjuknak: 'Bela jokedvu, bogarakat es magyar dalokat gyujt'. ... Julius 28-an Vesztorol Bekesre utazik"), src("GYUJ", "entry 4: 'June - July, 1905. Veszto (5)'")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1906-06-01", "matchesCollection": "2", "alsoMatchesCollections": ["5"],
  "title": "Sopron county: Jobahaza and Bogyoszlo",
  "dateStart": "1906-06", "dateEnd": "1906-06", "datePrecision": "month",
  "departure": {"place": "Pozsony", "evidence": "inferred", "note": "The chronology says he planned to travel to Pozsony, Sopron and Veszto in June; he was in Pozsony from June 2."},
  "stops": [stop("Jobahaza", "Jobahaza, Hungary", "Gyor-Moson-Sopron", "1906-06", "1906-06", "37 songs dated June 1906", country="HU"), stop("Bogyoszlo", "Bogyoszlo, Hungary", "Gyor-Moson-Sopron", "1906-06", "1906-06", "4 songs dated June 1906", country="HU")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "The chronology notes that 37 songs from Jobahaza and 4 from Bogyoszlo carry a June 1906 date and that a planned Sopron trip in June is the likely occasion. It also warns that for 1906 the field notes mostly give only the month and the singer's home, so the trip cannot be followed day by day.",
  "sources": [mek(85, "Bartok tervei szerint juniusban Pozsonyba, Sopronba, majd Vesztore ... A Sopron varmegyei Jobahazarol 37, Bogyoszlorol pedig 4 nepdal szarmazik 1906. juniusi datummal"), src("GYUJ", "entries 2 and 5")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1906-06-02", "matchesCollection": "3", "alsoMatchesCollections": ["6"],
  "title": "Tura (Pest county): two visits, first use of the phonograph",
  "dateStart": "1906-06-29", "dateEnd": "1906-07-09", "datePrecision": "day",
  "departure": {"place": "Budapest / Rakoskeresztur (guest of the Vecsey family)", "evidence": "documented"},
  "stops": [stop("Tura", "Tura, Hungary", "Pest", "1906-06-29", "1906-07-01", "Three days with the Hajdu family; 75 songs notated.", country="HU"), stop("Vacszentlaszlo (?)", "Vacszentlaszlo, Hungary", "Pest", "1906-07-01", "1906-07-01", "On July 1 'they go to a neighbouring village for the church feast'; the village is not named. The index lists Vacszentlaszlo, beginning of July 1906.", country="HU", confidence="inferred"), stop("Rakoskeresztur", "Budapest XVII, Hungary", "Pest", "1906-07-03", "1906-07-06", "Reports to his mother on the first Tura trip.", country="HU"), stop("Tura", "Tura, Hungary", "Pest", "1906-07-07", "1906-07-09", "Second visit; from here the phonograph is used. 151 songs from Tura in all, 76 on this second visit.", country="HU")],
  "return": {"place": "Rakoskeresztur", "date": "1906-07-09", "evidence": "inferred"},
  "companions": [], "romanianMaterial": False,
  "summary": "On 29 June 1906 Bartok went to Tura as guest of the Hajdu family and notated 75 songs in three days; he returned on 7 July for a second visit on which he first used the phonograph. The chronology gives 151 songs from Tura in total. The index's 'Vacszentlaszlo, beginning of July' probably corresponds to the church-feast visit to a neighbouring village on 1 July, but the chronology does not name it.",
  "sources": [mek(87, "Junius 29-en ... utazik Turara ... Harom napig ... 75 dalt jegyez le. Julius 1-en az egyik szomszed faluba mennek bucsuba. ... Julius 7-en megint Turara megy ... Ekkor kezdi hasznalni a fonografot ... Turan osszesen 151 dalt jegyzett le, 76-ot ezen a masodik uton."), src("GYUJ", "entries 3 and 6")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1906-07-01", "matchesCollection": "9", "alsoMatchesCollections": ["11", "14"],
  "title": "Bekes county: Gyula, Benedek, Feketeer puszta, Doboz",
  "dateStart": "1906-07-19", "dateEnd": "1906-07-25", "datePrecision": "day",
  "departure": {"place": "Rakoskeresztur", "evidence": "documented"},
  "stops": [stop("Gyula", "Gyula, Hungary", "Bekes", "1906-07-20", "1906-07-21", "Attempt to collect on July 20 without result; hotel.", country="HU"), stop("Benedek (Jozsefbenedek, Gyula)", "Gyula-Jozsefbenedek, Hungary", "Bekes", "1906-07-21", "1906-07-21", "No success on the 21st.", country="HU"), stop("Feketeer puszta (Sarkad)", "Sarkad, Hungary", "Bekes", "1906-07-22", "1906-07-22", "Introduced by Geza Galgoczy to the estate steward; collecting successful here.", country="HU"), stop("Benedek", "Gyula-Jozsefbenedek, Hungary", "Bekes", "1906-07-23", "1906-07-24", "Collects on the 23rd and 24th.", country="HU"), stop("Doboz", "Doboz, Hungary", "Bekes", "1906-07-24", "1906-07-25", "Visits relatives (Vidovszky); 83 songs and 47 recordings on the whole trip.", country="HU")],
  "return": {"place": "Rakoskeresztur via Bekescsaba", "date": "1906-07-25", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Around 19 July 1906 Bartok went to Bekes county, where estate stewards helped him find singers. After a fruitless start in Gyula and Benedek he collected at Feketeer puszta near Sarkad and then at Benedek and Doboz; the chronology counts 83 songs and 47 phonograph recordings for the trip. The index's Gyula, Doboz and Gyulavari entries belong to this area.",
  "sources": [mek(87, "Julius 19-e korul Bekes megyebe megy ... Julius 20-an Gyulan kiserel meg gyujtest eredmenytelenul ... 21-en Benedekre ... Julius 22-en ... Feketeer pusztara ... Julius 23-an es 24-en Benedeken gyujt, majd 24-en delutan Dobozra ... 83 dal es 47 felvetel"), src("GYUJ", "entries 9, 11, 14")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1906-08-01", "matchesCollection": "13", "alsoMatchesCollections": [],
  "title": "Tapioszele (Pest county)",
  "dateStart": "1906-08-15", "dateEnd": "1906-08-15", "datePrecision": "phrase",
  "departure": {"place": "Rakoskeresztur", "evidence": "documented"},
  "stops": [stop("Tapioszele", "Tapioszele, Hungary", "Pest", "1906-08", "1906-08", "Invited by Margit Bicskey; 32 songs. Date 'around the 15th' announced in a letter of August 4.", country="HU")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "On 4 August 1906 Bartok wrote to Margit Bicskey at Tapioszele that he would like to come and collect around the 15th; the chronology records 32 songs from Tapioszele.",
  "sources": [mek(88, "Augusztus 4-en ... Tapioszelere ... szeretne odamenni gyujteni 15-e korul. Gyujt is Tapioszelen 32 dalt."), src("GYUJ", "entry 13")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1906-08-02", "matchesCollection": "98", "alsoMatchesCollections": [],
  "title": "Gerlice puszta (Gomor county): Slovak-Hungarian language border, 120 songs",
  "dateStart": "1906-08-10", "dateEnd": "1906-08-21", "datePrecision": "phrase",
  "departure": {"place": "Tura", "evidence": "documented", "note": "'Turarol egyenesen folrandultam Gomorbe Gerlicere' (letter of August 21); the Tura visit meant is presumably a third one after the Tapioszele trip, the chronology does not date it."},
  "stops": [stop("Gerlice puszta (Ratko)", "Gerlica, Slovakia", "Revuca district", "1906-08", "1906-08-21", "120 songs, a third of them 'definitely Hungarian songs with Slovak text'.", country="SK")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "In a letter of 21 August 1906 Bartok told his mother that he had gone straight from Tura up to Gerlice in Gomor county and had notated 120 songs there, a third of them Hungarian melodies with Slovak texts. The exact days are not given.",
  "sources": [mek(88, "Augusztus 21-en edesanyjanak hosszasan beszamol gerlicei utjarol ... 'Turarol egyenesen folrandultam Gomorbe Gerlicere. ... Feljegyeztem 120 dalt'"), src("GYUJ", "entry 98: 'August 1906, Gomor county'")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1906-08-03", "matchesCollection": "19", "alsoMatchesCollections": ["17", "18", "10", "20", "15"],
  "title": "Szeged region from Kamaras: Szentes, Horgos, Szeged, Csongrad, Csanadapaca, Apatfalva, Nagyszentmiklos",
  "dateStart": "1906-08-25", "dateEnd": "1906-09-02", "datePrecision": "day",
  "departure": {"place": "Gerlice puszta / Budapest", "evidence": "inferred"},
  "stops": [stop("Kamaras (Szeged)", "Szeged, Hungary", "Csongrad-Csanad", "1906-08-25", "1906-08-31", "Base with the Baranyai family, from which he visited the villages: Szentes 19, Horgos 40, Szeged 49, Csongrad 5, Csanadapaca 2 songs.", country="HU"), stop("Szentes", "Szentes, Hungary", "Csongrad-Csanad", "1906-08", "1906-08", "19 songs", country="HU"), stop("Horgos", "Horgos, Serbia", "North Banat", "1906-08", "1906-08", "40 songs", country="RS"), stop("Szeged", "Szeged, Hungary", "Csongrad-Csanad", "1906-08-28", "1906-08-28", "49 songs; postcard to his mother from Szeged on August 28.", country="HU"), stop("Csongrad", "Csongrad, Hungary", "Csongrad-Csanad", "1906-08", "1906-08", "5 songs", country="HU"), stop("Apatfalva", "Apatfalva, Hungary", "Csongrad-Csanad", "1906-09-01", "1906-09-01", "26 songs on September 1.", country="HU"), stop("Nagyszentmiklos", "Sannicolau Mare", "Timis", "1906-09-02", "1906-09-02", "Visit to his birthplace (aunts, the agricultural school), then home; the index lists one record.")],
  "return": {"place": "Budapest via Szolnok", "date": "1906-09-05", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "From 25 August 1906 Bartok lodged at Kamaras near Szeged with the Baranyai family and collected in the surrounding towns and villages (Szentes, Horgos, Szeged, Csongrad, Csanadapaca), on 1 September at Apatfalva, and on 2 September visited his birthplace Nagyszentmiklos before travelling home via Szolnok. The order of the village visits within the week is not given.",
  "sources": [mek(88, "Augusztus 25-en Kamarasra megy ... Bartok Szentesen 19, Horgoson 40, Szegeden 49, Csongradon 5, Csanadapacan 2 dalt gyujtott. ... Szeptember 1-en Apatfalvan (Csanad varmegye) 26 dalt gyujt. Szeptember 2-an Nagyszentmiklosra latogat"), src("GYUJ", "entries 17, 18, 19, 10, 20, 15")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1906-09-01", "matchesCollection": "25", "alsoMatchesCollections": ["24"],
  "title": "Balaton: Pusztabereny (Balatonbereny) and Keszthely",
  "dateStart": "1906-09-25", "dateEnd": "1906-09-29", "datePrecision": "day",
  "departure": {"place": "Budapest (Huvosvolgy)", "evidence": "inferred"},
  "stops": [stop("Pusztabereny (Balatonbereny)", "Balatonbereny, Hungary", "Somogy", "1906-09-25", "1906-09-26", "Mail forwarded here c/o Albert Graner; 3 songs labelled Balatonbereny.", country="HU"), stop("Keszthely", "Keszthely, Hungary", "Zala", "1906-09-27", "1906-09-28", "41 songs (index: 42).", country="HU")],
  "return": {"place": "Budapest (letter posted at Pusztaszabolcs on September 29)", "date": "1906-09-29", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "At the end of September 1906 Bartok's mail was forwarded to Pusztabereny by Lake Balaton, where three songs labelled Balatonbereny were collected; around 27 September he was at Keszthely, the source of 41 songs, and on the 29th he posted a letter from Pusztaszabolcs on the way back.",
  "sources": [mek(89, "Szeptember 25-en postajat Pusztaberenybe ... Balatonbereny megjelolessel 3 dalt gyujt itt. Szeptember 27-e korul Keszthelyen jar, ahonnan 41 dal szarmazik."), src("GYUJ", "entries 24, 25")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1906-10-01", "matchesCollection": "96", "alsoMatchesCollections": [],
  "title": "Gerlice puszta (Gomor county), October 1906: Slovak songs",
  "dateStart": "1906-10-13", "dateEnd": "1906-11-02", "datePrecision": "phrase",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Gerlice puszta (Ratko)", "Gerlica, Slovakia", "Revuca district", "1906-10-13", "1906-11-02", "By October 15: 9 songs notated and 20 recorded; October 16 Slovak songs in a tavern; in three weeks about 150 Slovak songs notated and 80 recorded (letter of November 3 from Pozsony).", country="SK")],
  "return": {"place": "Pozsony", "date": "1906-11-02", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "After settling the Hungarian Folksongs publication in Budapest on 12 October 1906 Bartok went again to Gerlice puszta, where he collected Slovak songs (about 150 notated and 80 recorded in three weeks, by his letter of 3 November from Pozsony).",
  "sources": [mek(89, "Ezutan ujbol Gerlice pusztara utazik. Oktober 15-en kozli edesanyjaval, hogy mar 9 dalt jegyzett le, es 20-at vett fel fonografba ... Oktober 16-an egy kocsmaban tot dalokat gyujt. ... 3 het alatt osszesen 150 tot dalt jegyzett le es 80-at vett fel fonografra."), src("GYUJ", "entry 96: 'October, 1906, Gomor'")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1906-11-01", "matchesCollection": "103", "alsoMatchesCollections": ["27"],
  "title": "Bekes county, November-December 1906: Szilad puszta (Veszto) and Doboz",
  "dateStart": "1906-11-07", "dateEnd": "1906-12-12", "datePrecision": "day",
  "departure": {"place": "Budapest, after the Philharmonic concert of November 7", "evidence": "documented"},
  "stops": [stop("Veszto-Szilad puszta", "Veszto, Hungary", "Bekes", "1906-11-08", "1906-11-23", "Rest, then 'nepdalhajsza'; by November 19: 90 Hungarian and 130 Slovak songs since leaving Rakoskeresztur.", country="HU"), stop("Doboz", "Doboz, Hungary", "Bekes", "1906-11-24", "1906-12-11", "Letters from Doboz on November 24 and 25; 'kedves parasztjaim kozott kellemes orakat toltok'.", country="HU")],
  "return": {"place": "Budapest, night train from Szilad", "date": "1906-12-12", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Straight after his Budapest concert of 7 November 1906 Bartok travelled to his sister at Szilad puszta near Veszto, rested, and then collected in the area; on 24 November he was collecting at Doboz. He returned to Budapest on the night of 12 December. The index has 115 Doboz records for November and 19 Veszto records for November-December.",
  "sources": [mek(90, "November 7-en ... 10 orakor mar utra kel hugahoz, Szilad pusztara. ... November 24-en azonban mar Dobozrol ertesiti, hogy ott gyujt ... December 12-en ejszaka utazik Sziladrol Budapestre"), src("GYUJ", "entries 103, 27")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1907-03-01", "matchesCollection": "28", "alsoMatchesCollections": ["29"],
  "title": "Felsoireg (Tolna county), Easter 1907",
  "dateStart": "1907-03-24", "dateEnd": "1907-04-03", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Felsoireg-Csehipuszta", "Iregszemcse, Hungary", "Tolna", "1907-03-24", "1907-04-03", "Guest of Lajos Huber, estate steward; March 27-30 lodged at an inn in Felsoireg; back to the Hubers for Easter (March 31). 258 records online. The index's Felsonyek (beginning of April) is a neighbouring village; the chronology does not name it.", country="HU")],
  "return": {"place": "Budapest", "date": "1907-04-03", "evidence": "inferred", "note": "End date from the index label."},
  "companions": [], "romanianMaterial": False,
  "summary": "For the Easter holiday of 1907 Bartok went to Felsoireg-Csehipuszta in Tolna county as guest of Lajos Huber; on 24 March he wrote that he had resumed collecting, and from 27 to 30 March he lodged at an inn in the village. The trip is the source of the 258 Felsoireg records in the index (March 24 - April 3).",
  "sources": [mek(95, "Marcius 24-en (Viragvasarnap) Felsoiregrol irja ... 'ismet megkezdte gyujtomunkajat' ... Marcius 27-tol 30-ig Felsoiregen egy vendegloben lakik."), src("GYUJ", "entries 28, 29")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1907-06-01", "matchesCollection": "31", "alsoMatchesCollections": [],
  "title": "Jaszbereny, June 28 - July 1, 1907",
  "dateStart": "1907-06-28", "dateEnd": "1907-07-01", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Jaszbereny", "Jaszbereny, Hungary", "Jasz-Nagykun-Szolnok", "1907-06-28", "1907-07-01", "Guest of Stefi Geyer's parents; 'few songs found'.", country="HU")],
  "return": {"place": "Budapest, then departure for Transylvania on the evening of July 1", "date": "1907-07-01", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Immediately after the end of the academic year Bartok went on 28 June 1907 to Jaszbereny, staying with the parents of Stefi Geyer, and found few songs; on 1 July he sent his luggage home and left in the evening for his first Transylvanian trip.",
  "sources": [mek(97, "Junius 28-an elso utja Jaszberenybe vezet, ahol Geyer Stefi szuleinek vendege. Keves notat talal. Julius 1-en ... este elindul elso erdelyi utjara."), src("GYUJ", "entry 31")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1907-07-01", "matchesCollection": "43", "alsoMatchesCollections": [],
  "title": "Kalotaszeg: Korosfo and Banffyhunyad, then Brasso, early July 1907",
  "dateStart": "1907-07-02", "dateEnd": "1907-07-06", "datePrecision": "day",
  "departure": {"place": "Budapest (evening train, July 1)", "evidence": "documented"},
  "stops": [stop("Korosfo", "Izvoru Crisului", "Cluj", "1907-07-02", "1907-07-04", "With the carver Gyorgy Pentek-Gyugyi, from whom he ordered a carved desk; 8 records online."), stop("Banffyhunyad", "Huedin", "Cluj", "1907-07-05", "1907-07-05", "Enthusiastic letter to his mother about the region and costume."), stop("Brasso", "Brasov", "Brasov", "1907-07-06", "1907-07-06", "Sightseeing by carriage, visit to the 'hetfalusi csangok', not a collecting stop.")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "Bartok's first Transylvanian journey began on the night of 1 July 1907 in Kalotaszeg: at Korosfo he stayed with the wood-carver Gyorgy Pentek-Gyugyi, on 5 July he wrote from Banffyhunyad, and on 6 July he visited Brasso. From there he continued to Csik county (separate entry).",
  "sources": [mek(97, "Kalotaszeg videken (Kolozs varmegye), Korosfon, Pentek-Gyugyi Gyorgynel jar ... Julius 5-en Banffyhunyadrol ... Julius 6-an Brassoban"), src("GYUJ", "entry 43: 'Beginning of July, 1907. Korosfo (8)'")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1907-07-02", "matchesCollection": "33", "alsoMatchesCollections": ["32", "34", "35", "36", "37", "38", "39", "40", "41"],
  "title": "Csik and Gyergyo (Szekely land), July-August 1907: about two months",
  "dateStart": "1907-07-07", "dateEnd": "1907-08-20", "datePrecision": "phrase",
  "departure": {"place": "Brasso", "evidence": "inferred", "note": "After the Brasso visit of July 6; the chronology says the route can be followed only in outline."},
  "stops": [stop("Csikrakos", "Racu", "Harghita", "1907-07", "1907-07", "Poste restante address; songs dated July."), stop("Csikjenofalva", "Ineu (Carta)", "Harghita", "1907-07", "1907-07", "Songs dated July."), stop("Csikkarcfalva", "Carta", "Harghita", "1907-07-30", "1907-07-30", "Letter to Etelka Freund from Csikkarcfalva on July 30."), stop("Csikszentmihaly", "Mihaileni", "Harghita", "1907", "1907", "Songs dated 1907 only."), stop("Csikszenttamas", "Tomesti", "Harghita", "1907", "1907", "Songs dated 1907 only."), stop("Csikvacsarcsi", "Vacaresti", "Harghita", "1907", "1907", "Songs dated 1907 only (index: 'Vacsardi', 72 records)."), stop("Csikmadaras", "Madaras", "Harghita", "1907-07", "1907-08", "Named as a poste restante address; no records.", confidence="inferred"), stop("Gyergyoszentmiklos", "Gheorgheni", "Harghita", "1907-07", "1907-08-20", "Visited about every four days for mail; photograph dated there August 20."), stop("Gyergyotekeropatak", "Valea Stramba", "Harghita", "1907-08-07", "1907-08-07", "Letter of August 7; songs dated August."), stop("Gyergyoujfalu", "Suseni", "Harghita", "1907-08-09", "1907-08-09", "Letter to his mother, August 9; songs dated 1907."), stop("Kilyenfalva", "Chileni", "Harghita", "1907", "1907", "Songs dated 1907 only."), stop("Gyergyocsomafalva", "Ciumani", "Harghita", "1907-08", "1907-08", "Songs dated August.")],
  "return": {"place": "Budapest, then Szilad puszta (letter from there September 6)", "date": "1907-08-20", "evidence": "inferred", "note": "'Gyergyobol hazautazik'; the day is not given, the last dated document is August 20."},
  "companions": [], "romanianMaterial": False,
  "summary": "From early July to about 20 August 1907 Bartok collected among the Szekely of Csik county; the chronology can follow the route only in outline: he went to Gyergyoszentmiklos for mail about every four days and gave Csikrakos and Csikmadaras as poste restante addresses. Dated documents place him at Csikkarcfalva on 30 July, Gyergyotekeropatak on 7 August and Gyergyoujfalu on 9 August; a photograph is dated Gyergyoszentmiklos, 20 August. Songs from Csikrakos and Csikjenofalva are dated July, from Gyergyotekeropatak and Gyergyocsomafalva August, the rest 1907 only. On 17 August he wrote that he had 'found the Szekely melody types'.",
  "sources": [mek(97, "Ezutan indul kozel 2 honapos szekelyfoldi, kozelebbrol Csik varmegyei gyujtoutjara, ahol utja csak vazlatosan kovetheto. Altalaban 4 naponkent bejar Gyergyoszentmiklosra postaert ... Julius 30-an Csikkarcfalvarol ir ... juliusi megjelolessel Csikrakos es Csikjenofalva, altalaban 1907-es evszammal Csikszentmihaly, Csikszenttamas, Gyergyoujfalu, Csikkarcfalva, Kilyenfalva es Csikvacsarcsi, augusztusi datummal Gyergyotekeropatak es Gyergyocsomafalva"), mek(98, "Augusztus 20-an egy fenykepet Gyergyoszentmiklosrol keltezi. Gyergyobol hazautazik"), src("GYUJ", "entries 32-41")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1907-10-01", "matchesCollection": "102", "alsoMatchesCollections": [],
  "title": "Nyitra county, All Saints 1907: Zobordarazs, Kislapas, Lapas",
  "dateStart": "1907-10-27", "dateEnd": "1907-11-06", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Nyitra", "Nitra, Slovakia", "Nitra", "1907-10-28", "1907-10-28", "Postcard to his sister from Nyitra, October 28.", country="SK"), stop("Zobordarazs", "Drazovce (Nitra), Slovakia", "Nitra", "1907-11", "1907-11", "Songs dated November.", country="SK"), stop("Kislapas", "Male Lapasovce (Golianovo), Slovakia", "Nitra", "1907-11", "1907-11", "Songs dated November.", country="SK"), stop("Lapas", "Velky Lapas, Slovakia", "Nitra", "1907-11", "1907-11", "Songs dated November.", country="SK")],
  "return": {"place": "Budapest (Terez korut)", "date": "1907-11-06", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Using the All Saints holiday of 1907 Bartok went to Nyitra county; a postcard from Nyitra is dated 28 October and songs from Zobordarazs, Kislapas and Lapas carry a November date. He was back in Budapest on 6 November. The index entry 'November 1907. Nyitra county (Zobordarazs)' has no records online.",
  "sources": [mek(98, "A Mindenszentek unnepet kihasznalando, Bartok Nyitra varmegyebe utazik. Oktober 28-an Nyitrarol ... Novemberi keltezessel Zobordarazs, Kislapas es Lapas kozsegekbol szarmazo dalok szerepelnek gyujteseben. ... November 6-an hazaerkezik"), src("GYUJ", "entry 102")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1908-03-01", "matchesCollection": "45", "alsoMatchesCollections": [],
  "title": "Korosfo, March 1908",
  "dateStart": "1908-03-01", "dateEnd": "1908-03", "datePrecision": "month",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Korosfo", "Izvoru Crisului", "Cluj", "1908-03-01", "1908-03", "'Marcius 1-en Korosfore utazik es ott folytatja a nepdalgyujtest'; 31 records online.")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "On 1 March 1908 Bartok travelled to Korosfo in Kalotaszeg and continued collecting there; the chronology gives no end date. The index lists 31 records for March 1908.",
  "sources": [mek(100, "Marcius 1-en Korosfore (Kolozs varmegye) utazik es ott folytatja a nepdalgyujtest."), src("GYUJ", "entry 45")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1908-10-01", "matchesCollection": "46", "alsoMatchesCollections": ["53"],
  "title": "Aranyosszek: Torda, Torocko and Szekelyhidas, October 1908 (first Romanian melodies)",
  "dateStart": "1908-10-04", "dateEnd": "1908-10-08", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "inferred"},
  "stops": [stop("Torda", "Turda", "Cluj", "1908-10-05", "1908-10-06", "Postcard from Torda, October 5; excursion to the Turda gorge on the 6th."), stop("Torocko", "Rimetea", "Alba", "1908-10-07", "1908-10-07", "Letter from Torocko, October 7; 7 records online."), stop("Szekelyhidas", "Podeni", "Cluj", "1908-10", "1908-10", "Kelemen: the first four Romanian melodies of the collection, notated in the mixed village of Szekelyhidas near Torocko, no phonograph, texts incomplete; he dates them November 1908, the chronology places the Aranyosszek trip in early October and does not name the village.", confidence="inferred")],
  "return": {"place": "Budapest", "date": "1908-10-08", "evidence": "inferred", "note": "Back in Budapest before the Nyitra trip of October 18."},
  "companions": [], "romanianMaterial": True,
  "summary": "In early October 1908 Bartok went to Aranyosszek: a postcard from Torda is dated 5 October and a letter from Torocko 7 October. Kelemen identifies the first Romanian melodies in Bartok's collection as four songs notated at Szekelyhidas (Podeni), a mixed village near Torocko, which he dates November 1908; the index entry 'Beginning of October, 1908. Torocko / Szekelyhidas' corresponds to this trip.",
  "sources": [mek(103, "Oktober elejen Bartok Aranyosszekre megy. Oktober 5-en Tordarol ... Oktober 7-en Torockorol ir Freund Irmanak."), kel(399, "az elso roman dallamokat 1908 novembereben jegyezte le Bartok a Toroczko kozeleben fekvo, vegyes lakossagu faluban Szekelyhidason (Podeni). Mindossze 4 dallamrol van szo."), kel(410, "locality list, Torda-Aranyos: 133. Podeni / Szekelyhidas 1908. XI."), src("GYUJ", "entries 46, 53")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1908-10-02", "matchesCollection": "48", "alsoMatchesCollections": [],
  "title": "Nyitra county: Tokesujfalu and Apatkolos, October 18, 1908",
  "dateStart": "1908-10-18", "dateEnd": "1908-10-18", "datePrecision": "day",
  "departure": {"place": "Budapest via Ersekujvar", "evidence": "documented"},
  "stops": [stop("Tokesujfalu", "Klatova Nova Ves, Slovakia", "Partizanske district", "1908-10-18", "1908-10-18", "Collects folk songs.", country="SK"), stop("Apatkolos", "Klatova Nova Ves (Opatovce?), Slovakia", "Partizanske district", "1908-10-18", "1908-10-18", "Collects folk songs.", country="SK", confidence="inferred")],
  "return": None, "companions": [], "romanianMaterial": False,
  "summary": "On 18 October 1908, travelling through Ersekujvar, Bartok collected folk songs in Tokesujfalu and Apatkolos in Nyitra county. The index entry has no records online.",
  "sources": [mek(103, "Oktober 18-an Ersekujvaron keresztulutazva Tokesujfalu es Apatkolos kozsegekben gyujt nepdalokat."), src("GYUJ", "entry 48")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1908-10-03", "matchesCollection": "47", "alsoMatchesCollections": [],
  "title": "Banffyhunyad, All Saints 1908",
  "dateStart": "1908-10-31", "dateEnd": "1908-11-06", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Banffyhunyad", "Huedin", "Cluj", "1908-10-31", "1908-11-05", "Lodged at the Tigris hotel; 14 records online."), stop("Kolozsvar", "Cluj-Napoca", "Cluj", "1908-11-05", "1908-11-06", "Not a collecting stop.")],
  "return": {"place": "Budapest", "date": "1908-11-06", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Using the All Saints holiday, Bartok travelled on 31 October 1908 to Banffyhunyad, where he stayed at the Tigris hotel; on 5 November he went on to Kolozsvar and on 6 November returned to Budapest.",
  "sources": [mek(103, "Oktober 31-en, a Mindenszentek unnepet kihasznalva Banffyhunyadra utazik, a Tigris szallodaban szall meg. ... November 5-en Banffyhunyadrol Kolozsvarra utazik ... November 6-an visszautazik Budapestre."), src("GYUJ", "entry 47")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1909-02-01", "matchesCollection": "49", "alsoMatchesCollections": [],
  "title": "Zobordarazs (Nyitra county), February 3-4, 1909",
  "dateStart": "1909-02-01", "dateEnd": "1909-02-05", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Nyitra", "Nitra, Slovakia", "Nitra", "1909-02-02", "1909-02-02", "Letter to his mother from Nyitra.", country="SK"), stop("Zobordarazs", "Drazovce, Slovakia", "Nitra", "1909-02-02", "1909-02-04", "Sleeps there and collects about 65 songs on February 3 and 4.", country="SK")],
  "return": {"place": "Budapest", "date": "1909-02-05", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "Using the Candlemas holiday Bartok went on 1 February 1909 to Nyitra county, slept at Zobordarazs and collected about 65 songs there on 3 and 4 February, returning to Budapest on the 5th.",
  "sources": [mek(105, "Februar 2-an Nyitrarol azt irja edesanyjanak ... Zobordarazson alszik, es ott gyujt mintegy 65 nepdalt, reszben februar 3-an, reszben 4-en ... Februar 5-en visszater Budapestre."), src("GYUJ", "entry 49")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1909-07-01", "matchesCollection": "50", "alsoMatchesCollections": ["52"],
  "title": "Bihar county, upper Fekete-Koros valley (Belenyes district), July-August 1909: first systematic Romanian collecting",
  "dateStart": "1909-07-17", "dateEnd": "1909-08-16", "datePrecision": "day",
  "departure": {"place": "Veszto (Szilad puszta), his sister's home", "evidence": "documented"},
  "stops": [stop("Nagyvarad", "Oradea", "Bihor", "1909-07-17", "1909-07-17", "Eight-hour wait between trains on the way to Belenyes."), stop("Belenyes", "Beius", "Bihor", "1909-07-17", "1909-08-07", "Base with the family of Ioan Busitia; 'mindig vissza-visszajovok Belenyesre, ahol jo a koszt' (July 27). 14 days in all according to his letter of August 31. Songs dated July."), stop("Gyalany", "Delani", "Bihor", "1909-07", "1909-07", "Songs dated July."), stop("Lehecseny", "Leheceni", "Bihor", "1909-07", "1909-08", "Songs dated July and again August."), stop("Hatar", "Hotarel", "Bihor", "1909-07", "1909-07", "Songs dated July."), stop("Biharmezo", "Poiana", "Bihor", "1909-07", "1909-08", "Songs dated July and again August."), stop("Telek", "Tileagd? (Kelemen: Tielec / Telek)", "Bihor", "1909-07", "1909-07", "Songs dated July."), stop("Lelesd", "Lelesti", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Bondoraszo", "Budureasa", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Kereszely", "Cresuia", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Biharkristyor", "Cristioru de Jos", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Draganfalva", "Draganesti", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Belenyesszentmarton", "Sanmartin de Beius", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Korossebes", "Sebis", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Vaskohszeleste", "Salistea de Vascau", "Bihor", "1909-08", "1909-08", "Songs dated August."), stop("Veszto-Szilad puszta", "Veszto, Hungary", "Bekes", "1909-08-07", "1909-08-16", "Fell ill about August 7 and went to his sister's; thanks the Busitias on August 14. The index's 'August 1909. Veszto (21)' records fall in this convalescence; the 25 Hungarian and 20 Slovak songs of the summer were collected at Veszto.", country="HU")],
  "return": {"place": "Budapest", "date": "1909-08-16", "evidence": "documented"},
  "companions": ["Ioan Busitia (Busitia Janos), teacher at the Romanian gymnasium in Belenyes, host and organiser"],
  "romanianMaterial": True,
  "summary": "Bartok's systematic Romanian collecting began on 17 July 1909, when he travelled from Veszto via Nagyvarad to Belenyes, where Ioan Busitia had prepared the ground; he returned repeatedly to Belenyes as his base and worked in the villages of the upper Fekete-Koros valley. Villages with July-dated songs are Belenyes, Gyalany, Lehecseny, Hatar, Biharmezo and Telek; August-dated are Lelesd, Bondoraszo, Kereszely, Biharkristyor, Draganfalva, Belenyesszentmarton, Korossebes and Vaskohszeleste, plus Lehecseny and Biharmezo again. Around 7 August he fell ill in the heat and went to his sister at Szilad puszta; by his own count the summer yielded 320 Romanian songs (Kelemen: he arrived 17 July and started work the next day; the trip lasted over two weeks). The order of the village visits is not documented.",
  "sources": [mek(107, "Julius 17-en Vesztorol Belenyesre utazik. ... Julius 19-en Belenyesrol ir levelezolapot edesanyjanak, majd megkezdi a gyujtest a Belenyes kornyeki falvakban, a Fekete-Koros volgyeben. ... Juliusi keltezessel Belenyes, Gyalany, Lehecseny, Hatar, Biharmezo es Telek, augusztusival Lelesd, Bondoraszo, Kereszely, Biharkristyor, Draganfalva, Belenyesszentmarton, Korossebes es Vaskohszeleste, valamint ujbol Lehecseny es Biharmezo"), mek(108, "Osszeallitasa szerint 25 magyar, 20 szlovak es 320 roman dalt gyujtott a nyaron ... Augusztus 7. korul megbetegszik es hugahoz utazik Sziladra. ... Augusztus 16. korul Budapestre utazik."), kel(400, "Elso gyujtoutjara elindulva, Belenyesre julius 17-en erkezett meg, s a kovetkezo napon mar munkahoz is latott. ... tobb mint ket hetig tartott. ... Megbetegedett"), kel(407, "locality list, Bihar: Beius, Budureasa VIII.1909, Cresuia, Cristior, Delani VII.1909, Draganesti, Hotarel, Leheceni, Lelesti, Poiana, Salistea-de-Vascau, Sanmartinul-de-Beius, Sebis VIII.1909, Tielec"), src("GYUJ", "entries 50, 52")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1909-08-01", "matchesCollection": "51", "alsoMatchesCollections": [],
  "title": "Mezoseg (Torda-Aranyos county): Mezokok and Alsodetrehem, end of August 1909",
  "dateStart": "1909-08-28", "dateEnd": "1909-09-04", "datePrecision": "phrase",
  "departure": {"place": "Budapest (after visiting his mother at St. Ruprecht an der Raab, August 23-24)", "evidence": "documented"},
  "stops": [stop("Mezokok", "Cooc (Cauaceu? see note)", "Cluj", "1909-08-31", "1909-08-31", "Postcard to Etelka Freund dated Mezokok, August 31; postcard to Istvan Thoman dated 'Beszterce-Marosludas' (written in transit). RFM dates the songs IX.1909.", confidence=None), stop("Alsodetrehem", "Tritenii de Jos", "Cluj", "1909-08", "1909-09", "Songs from Alsodetrehem and Mezokok collected in this period; RFM dates them IX.1909.")],
  "return": None, "companions": [], "romanianMaterial": True,
  "summary": "At the end of August 1909 Bartok travelled to the Mezoseg in central Transylvania; on 31 August he wrote from Mezokok, and the songs of this trip come from Mezokok and Alsodetrehem in Torda-Aranyos county. The melody data in RFM give September 1909, while two postcards are dated 31 August; Kelemen concludes the collecting fell in the last days of August and the first of September.",
  "sources": [mek(108, "Augusztus vegen Erdely kozepso reszere, a Mezosegbe utazik. Augusztus 31-en Mezokokrol (Torda-Aranyos varmegye) levelezolapot ir ... mezokoki es alsodetrehemi ... eredetu nepdalokat gyujt."), kel(400, "Masodik gyujtoutja augusztus vegen, Torda-Aranyos megye mezosegi reszere vezetett. Alsodetrehem es Mezokok kozsegekben jart."), kel(414, "note 9: A dallamoknal gyujtesi idopontkent 1909 IX. ho olvashato. Ugyanakkor ket levelezolapjan is augusztus 31-es datum olvashato ... a mezosegi gyujtes idopontjat augusztus utolso napjaiban is megjelolhetjuk."), src("GYUJ", "entry 51")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1910-01-01", "matchesCollection": "55", "alsoMatchesCollections": [],
  "title": "Nagyszentmiklos (Torontal county), January 1910",
  "dateStart": "1910-01", "dateEnd": "1910-01", "datePrecision": "month",
  "departure": {"place": "Budapest", "evidence": "inferred", "note": "He returned from Paris on January 5 and was in Budapest on January 8 and 12; the chronology does not record the Nagyszentmiklos visit."},
  "stops": [stop("Nagyszentmiklos", "Sannicolau Mare", "Timis", "1910-01", "1910-01", "Bartok's birthplace. RFM IV prints 'Sanmiclausul mare (Torontal), un fecior / un om, I. 1910' under several colinde (mus. ex. 10h, 53a, 87i, 122e); Kelemen lists Sannicolaul-Mare, 1910. I.")],
  "return": None, "companions": [], "romanianMaterial": True,
  "summary": "The colinde source data in Rumanian Folk Music IV and Kelemen's locality list date a group of melodies from Nagyszentmiklos, Bartok's birthplace, to January 1910; Kelemen counts it as one of three collecting trips of early 1910. The day-by-day chronology does not mention the visit, so the exact days and the route are unknown.",
  "sources": [src("RFM4", "source data under mus. ex. 10h (M.F. 856c), 53a (M.F. 846b), 87i (M.F. 846c), 122e (M.F. 831a): 'Sanmiclausul mare (Torontal), ... I. 1910'"), kel(400, "Az 1910-es ev elejen harom gyujtoutjarol tudunk. Januarban szulohelyen Nagyszentmikloson ... gyujt."), kel(410, "locality list, Torontal: 122. Sannicolaul-Mare / Nagyszentmiklos 1910. I."), src("GYUJ", "entry 55")],
  "evidenceQuality": "dates only",
 },
 {
  "id": "cur-1910-02-01", "matchesCollection": "56", "alsoMatchesCollections": [],
  "title": "Bihar county: Belenyes and the Vaskoh district, February 1910",
  "dateStart": "1910-02-05", "dateEnd": "1910-02-13", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented", "note": "Planned since January 3 (letter from Paris), final programme sent to Busitia January 28."},
  "stops": [stop("Belenyes", "Beius", "Bihor", "1910-02-05", "1910-02-06", "Arrives on the morning of February 5; collecting from the 6th for about a week in the Fekete-Koros valley."), stop("Vaskohmezo", "Camp", "Bihor", "1910-02", "1910-02", "Kelemen: Camp 1910. II."), stop("Kerpenyed", "Carpinet", "Bihor", "1910-02", "1910-02", "Kelemen: Carpinet 1910. II."), stop("Vaskoh", "Vascau", "Bihor", "1910-02", "1910-02", "Kelemen: Vascau 1910. II.")],
  "return": {"place": "Budapest (sonata recital there on February 28)", "date": "1910-02-13", "evidence": "inferred", "note": "'korulbelul egy hetig' from February 6."},
  "companions": ["Ioan Busitia (organised the programme)"],
  "romanianMaterial": True,
  "summary": "After planning the trip with Busitia since early January, Bartok arrived at Belenyes on the morning of 5 February 1910 and from the 6th collected for about a week in the Fekete-Koros valley, in Belenyes, Vaskohmezo, Kerpenyed and Vaskoh. The index entry 'February, 1910. Upper region of the river Fekete-Koros: district of Belenyes and Vaskoh' has no records online.",
  "sources": [mek(110, "Januar 3. Parizsbol ertesiti Busitia Janosnet Belenyesen arrol, hogy a honap vegen Vaskoh tajekara keszul. ... Januar 9-en ujbol ir ... Januar 28-a megirja Busitia Janosnak vegleges vaskohi programjat."), mek(111, "Februar 5-en reggel megerkezik Belenyesre, majd februar 6-tol korulbelul egy hetig a Fekete-Koros volgyeben gyujt, Belenyes, Vaskohmezo, Kerpenyed es Vaskoh kozsegekben."), kel(407, "locality list, Bihar: Camp / Vaskohmezo 1910 II.; Carpinet / Kerpenyed 1910. II.; Vascau / Vaskoh 1910. II."), src("GYUJ", "entry 56")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1910-03-01", "matchesCollection": "58", "alsoMatchesCollections": ["59"],
  "title": "Kalotaszeg at Easter 1910: Korosfo and Magyargyeromonostor",
  "dateStart": "1910-03-21", "dateEnd": "1910-04-04", "datePrecision": "phrase",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Korosfo", "Izvoru Crisului", "Cluj", "1910-03-21", "1910-04-03", "'Marcius vegen (Husvet heteben) Bartok Korosfore megy' (Easter Sunday 1910 = March 27); 6 records online dated April."), stop("Magyargyeromonostor", "Manastireni", "Cluj", "1910-03", "1910-04", "Kelemen: in March he notated Hungarian and Romanian folk music at Magyargyeromonostor; probably also the few Bisztra melodies dated III.1910 in the Colinde volume (sung by a young man 'of higher schooling'). Index: 23 records, end of March - April.")],
  "return": {"place": "Budapest (letter from there April 5)", "date": "1910-04-04", "evidence": "inferred"},
  "companions": [], "romanianMaterial": True,
  "summary": "In Easter week 1910 (Easter Sunday 27 March) Bartok went to Korosfo in Kalotaszeg; Kelemen adds that in March he notated Hungarian and Romanian material at nearby Magyargyeromonostor, where he probably also recorded the Bisztra songs dated March 1910 in the Colinde volume. He was writing from Budapest again on 5 April.",
  "sources": [mek(112, "Marcius vegen (Husvet heteben) Bartok Korosfore megy ... Aprilis 5-en Budapestrol ir Zurichbe"), kel(400, "Marciusban magyar es roman nepzenet jegyez le Magyargyeromonostoron. Alighanem azt a nehany Bisztrarol szarmazo dallamot is itt vehette fonografra, amelyeknek gyujtesi idopontja a kolinda-kotetben, 1910. III. ho megjelolessel szerepel."), kel(408, "locality list, Kolozs: 68. Manastireni / Magyargyeromonostor 1910. III."), src("GYUJ", "entries 58, 59")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1910-10-01", "matchesCollection": "60", "alsoMatchesCollections": [],
  "title": "Kis-Szamos region (Szolnok-Doboka county): Szamosujvar, October 14-18, 1910",
  "dateStart": "1910-10-14", "dateEnd": "1910-10-18", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Kolozsvar", "Cluj-Napoca", "Cluj", "1910-10-14", "1910-10-15", "Transit."), stop("Szamosujvar", "Gherla", "Cluj", "1910-10-15", "1910-10-17", "Letters from here October 17: 'Obligat fonografromlassal zarodott ez a kirandulas is ... eredmeny eleg van'. Kelemen: Gherla 1910. XI. [sic]."), stop("Kendilona", "Luna de Jos", "Cluj", "1910-10", "1910-10", "Kelemen locality list (dated 1910. XI. there); the chronology names only Szamosujvar.", confidence="inferred"), stop("Fuzesmikola", "Nicula", "Cluj", "1910-10", "1910-10", "Kelemen locality list (dated 1910. XI. there).", confidence="inferred"), stop("Kolozsvar", "Cluj-Napoca", "Cluj", "1910-10-17", "1910-10-18", "Return via Kolozsvar.")],
  "return": {"place": "Budapest", "date": "1910-10-18", "evidence": "documented"},
  "companions": [], "romanianMaterial": True,
  "summary": "On 14 October 1910 Bartok travelled from Budapest to Kolozsvar and on the 15th to Szamosujvar in Szolnok-Doboka county; on 17 October he reported that the excursion had ended with the usual phonograph breakdown but with enough results, and on the 18th he was back in Budapest. Kelemen's locality list gives Gherla, Luna de Jos (Kendilona) and Nicula (Fuzesmikola) for this county but dates them November 1910; the chronology's dates are 14-18 October, matching the index label.",
  "sources": [mek(116, "Oktober 14-en Budapestrol Kolozsvarra, 15-en Szamosujvarra (Szolnok-Doboka varmegye) utazik. Oktober 17-en innen ir levelezolapot ... 'Obligat fonografromlassal zarodott ez a kirandulas is. ... eredmeny eleg van'. ... Oktober 18-an ismet Budapesten."), kel(400, "Novemberben Szolnok-Doboka megyei falvakat keres fel."), kel(410, "locality list, Szolnok-Doboka: Gherla, Luna-de-Jos, Micola [Nicula], ? - 1910. XI."), src("GYUJ", "entry 60")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1910-11-01", "matchesCollection": "57", "alsoMatchesCollections": ["61"],
  "title": "Csallokoz and Hont: Nagymegyer (November 5-6 and 16) and the Ipolysag horn and bagpipe competition (November 13), 1910",
  "dateStart": "1910-11-04", "dateEnd": "1910-11-16", "datePrecision": "day",
  "departure": {"place": "Budapest", "evidence": "documented"},
  "stops": [stop("Nagymegyer", "Velky Meder, Slovakia", "Dunajska Streda district", "1910-11-05", "1910-11-06", "Collects in the Csallokoz.", country="SK"), stop("Szeged", "Szeged, Hungary", "Csongrad-Csanad", "1910-11-10", "1910-11-10", "Trio concert, not collecting.", country="HU"), stop("Ipolysag", "Sahy, Slovakia", "Levice district", "1910-11-13", "1910-11-13", "Shepherd's horn and bagpipe competition organised by the Hont county archive (circular of November 4); 54 records online.", country="SK"), stop("Nagymegyer", "Velky Meder, Slovakia", "Dunajska Streda district", "1910-11-16", "1910-11-16", "Second visit, then on to Komarom.", country="SK")],
  "return": {"place": "Komarom / Budapest", "date": "1910-11-16", "evidence": "documented"},
  "companions": [], "romanianMaterial": False,
  "summary": "After his All Saints collecting Bartok worked at Nagymegyer in the Csallokoz on 5 and 6 November 1910, attended the shepherd's-horn and bagpipe competition at Ipolysag on 13 November 'to his great joy', and was again at Nagymegyer on 16 November before going on to Komarom. The index's Nagymegyer entry also names an end-of-March to early-April 1910 period that the chronology does not confirm (he was in Paris until 14 March and at Korosfo in Easter week).",
  "sources": [mek(116, "November 5-en es 6-an a Csallokozben, Nagymegyeren (Komarom varmegye) gyujt Bartok."), mek(117, "November 13. Tulok- es dudaverseny Ipolysagon (Hont varmegye), Bartok nagy oromere. ... November 16-an megint Nagymegyeren jar, onnan utazik Komaromba."), src("GYUJ", "entries 57, 61")],
  "evidenceQuality": "documented itinerary",
 },
 {
  "id": "cur-1910-12-01", "matchesCollection": "64", "alsoMatchesCollections": ["65"],
  "title": "Mocvidek (Torda-Aranyos and Also-Feher counties), Christmas 1910 - January 1911",
  "dateStart": "1910-12-24", "dateEnd": "1911-01-05", "datePrecision": "day",
  "departure": {"place": "Budapest; 60 phonograph cylinders sent ahead, 100 carried", "evidence": "documented"},
  "stops": [stop("Abrudbanya", "Abrud", "Alba", "1910-12-25", "1910-12-28", "Lodging December 25-28; 'ott nem lehet gyujteni'."), stop("Kerpenyes", "Carpinis (Rosia Montana)", "Alba", "1910-12-27", "1910-12-27", "45 songs from 10 in the morning to 9 at night, then back to Abrudbanya on foot. Kelemen/RFM: Carpinis 1910. XII."), stop("Topanfalva", "Campeni", "Alba", "1910-12-28", "1911-01-04", "Base from December 28; cylinders sent here January 2-3; postcard from here January 4."), stop("Fehervolgy", "Albac", "Alba", "1910-12-29", "1910-12-31", "Closed postcard December 29 describing the scattered settlements; census taken there December 31. 'korulbelul 150 szamot kaptam, a melynek fele azonban nem dal, hanem tanc hegedu, havasi kurtjel, furulyazas'."), stop("Feketevolgy", "Neagra", "Alba", "1910-12", "1910-12", "Named among the villages collected in Torda-Aranyos; order not given."), stop("Kozepvidra", "Vidra (middle part)", "Alba", "1910-12", "1910-12", "Kelemen: no such village in the gazetteers; the scattered settlement between Also- and Felsovidra."), stop("Bisztra", "Bistra", "Alba", "1910-12", "1910-12", "Kelemen/RFM: Bistra 1910. XII."), stop("Alsovidra", "Vidra", "Alba", "1910-12", "1910-12", "Kelemen/RFM: Vidra-de-Mijloc 1910. XII."), stop("Felsovidra", "Avram Iancu", "Alba", "1910-12", "1910-12", "Kelemen/RFM: Vidra-de-Sus 1910. XII."), stop("Fenes", "Fenes (Zlatna)", "Alba", "1911-01", "1911-01", "Also-Feher county; RFM IV: 'Fenes (Alba de jos), feciori, I. 1911'; the chronology: after January 4 'tovabbi utra indul az Aranyos menten Torda fele'."), stop("Ompolykovesd", "Petrosani (Zlatna), Alba", "Alba", "1911-01", "1911-01", "RFM IV: 'Petrosan (Alba de jos), feciori, I. 1911'. Kelemen note 2: HNT 1907 Petrosan; RFM Petrozsany.")],
  "return": {"place": "Budapest (Bluebeard's Castle begun in February; Bihar trip planned February 16)", "date": "1911-01-05", "evidence": "inferred", "note": "The chronology's last dated document is the January 4 postcard from Topanfalva; the further route along the Aranyos towards Torda is undated."},
  "companions": [], "romanianMaterial": True,
  "summary": "Bartok used the Christmas holiday of 1910 for a trip among the Moti of the Aranyos valley: he arrived in Transylvania on 24 December, lodged at Abrudbanya from the 25th to the 28th, collected 45 songs at Kerpenyes on the 27th, moved his base to Topanfalva on the 28th and wrote from Fehervolgy on the 29th and 31st, where he was counted in the census. The villages of the trip are Feketevolgy, Kozepvidra, Fehervolgy, Bisztra, Also- and Felsovidra in Torda-Aranyos county; his wife sent fresh cylinders to Topanfalva on 2 and 3 January 1911, and on 4 January he set off along the Aranyos towards Torda. Kelemen adds that some villages of neighbouring Also-Feher county (Fenes, Ompolykovesd, dated January 1911 in RFM) were visited on the same trip. About half of the roughly 150 items were instrumental (fiddle dances, alphorn signals, flute).",
  "sources": [mek(117, "December 24-en erkezik Erdelybe, 25-tol 28-ig Abrudbanyan ... szall meg. December 27-en Kerpenyesen ... gyujt, reggel 10-tol este 9-ig 45 dalt ... December 28-an ... atmegy Topanfalvara ... December 29-en zart levelezolapot kuld felesegenek Fehervolgy (roman neven Albac) kozsegbol"), mek(118, "Torda-Aranyos varmegyeben Feketevolgy, Kozepvidra, Fehervolgy, Bisztra, Also- es Felsovidra kozsegekben gyujt. December 31-en a nepszamlalas idejen Fehervolgyon jar ... Januar 2-an hengerei fogytan vannak, igy felesege 25, 3-an pedig ujabb 30 hengert kuld ... Topanfalvara. Januar 4-en innen ir levelezolapot ... majd tovabbi utra indul az Aranyos menten Torda fele."), kel(400, "Ez alkalommal Torda-Aranyos megyeben a Topanfalva kornyeken elo mocok kozott gyujtott. ... A gyujtout a kovetkezo ev, 1911 januarjanak elso napjaira is atnyult. Nehany, Torda-Aranyoshoz kozel fekvo Also-Feher megyei faluban is jart ekkor Bartok"), kel(407, "locality list, Also-Feher: Carpinis / Abrudkerpenyes 1910. XII.; Fenes 1911. I.; Petrosan / Ompolykovesd 1911. I.; ? 1911. I. (4 localities, 126 melodies)"), kel(410, "locality list, Torda-Aranyos: Albac, Albac-Gura-Aradi, Bistra, Neagra, Vidra-de-Mijloc, Vidra-de-Sus 1910. XII."), src("GYUJ", "entries 64, 65")],
  "evidenceQuality": "documented itinerary",
 },
]
