/* eslint-disable */
// Generated by scripts/gen-types.mjs from australia/data/schema/facets.schema.json. Do not edit by hand.

/**
 * facets.json: for each facet, a map of value -> number of songs. Keys are sorted. Null values are counted under the key 'null'.
 */
export interface Facets {
  _meta: {
    songCount: number
    builtWith?: string | null
  }
  decade: CountMap
  year: CountMap
  kind: CountMap
  state: CountMap
  town: CountMap
  newspaper: CountMap
  songbook: CountMap
  singer: CountMap
  collector: CountMap
  author: CountMap
  hasNotation: CountMap
  hasMidi: CountMap
  yearFrom: CountMap
  hasMasthead: CountMap
  hasAudio: CountMap
}
export interface CountMap {
  [k: string]: number | undefined
}
