/* eslint-disable */
// Generated by scripts/gen-types.mjs from australia/data/schema/place.schema.json. Do not edit by hand.

/**
 * One node of the place hierarchy in places.json (country > state > town). Songs sit at the town of the newspaper that printed them, or at the state when only that is known.
 */
export interface Place {
  id: string
  type: 'country' | 'state' | 'town'
  name: string
  parent: string | null
  state: string | null
  lat: number | null
  lng: number | null
  coordSource: 'fixed' | 'gazetteer' | null
  counts: {
    total: number
    byDecade: CountMap
    byKind: CountMap
  }
  years: {
    min: number | null
    max: number | null
  }
  songIds: string[]
  newspapers: CountMap
}
export interface CountMap {
  [k: string]: number | undefined
}
