/* eslint-disable */
// Generated by scripts/gen-types.mjs from australia/data/schema/song.schema.json. Do not edit by hand.

/**
 * Canonical record for one song or poem indexed from folkstream.com (Australian Folk Songs, Mark Gregory). Unknown values are null, never invented. Every derived field keeps the raw text it came from.
 */
export interface Song {
  /**
   * Stable id: 'afs-' + the page number of the record on folkstream.com (001.html -> afs-001).
   */
  id: string
  source: {
    site: 'afs'
    siteName: string
    /**
     * The page number as it appears in the URL.
     */
    siteId: string
    /**
     * Record page on folkstream.com, exactly as fetched.
     */
    url: string
    fetchedAt: string | null
  }
  /**
   * Title without the trailing year.
   */
  title: string
  /**
   * Title as printed in the page <title>, including the year.
   */
  titleRaw: string | null
  /**
   * Other titles the songs index lists the same page under.
   */
  titleAlt: string[]
  /**
   * song when notation, a MIDI file or a tune is mentioned; poem only on an explicit signal; else unknown.
   */
  kind: 'song' | 'poem' | 'unknown'
  year: {
    value: number | null
    /**
     * true for '1860s' or 'c. 1890' in the title.
     */
    approx: boolean
    from: 'title' | 'index' | 'newspaper' | 'notes' | null
    decade: string | null
  }
  author: {
    /**
     * From 'written by X' in the notes, a 'By X' line, or a one-line signature after the last stanza.
     */
    name: string | null
    raw: string | null
    /**
     * A one-line final stanza such as 'H.S.B., Dunmore.' kept verbatim.
     */
    signature: string | null
  }
  text: {
    incipit: string | null
    stanzas: string[][]
    lineCount: number
    wordCount: number
  }
  notes: {
    /**
     * Mark Gregory's notes, as plain text with paragraph breaks.
     */
    text: string | null
    links: {
      text: string | null
      href: string
    }[]
  }
  provenance: {
    newspaper: {
      title: string
      /**
       * Folded lookup key into data/newspapers.json.
       */
      key: string
      troveArticleId: string | null
      troveUrl: string | null
      date: {
        year: number
        month: number | null
        day: number | null
        raw: string
      } | null
      page: number | null
      /**
       * The words before 'newspaper' in the notes, e.g. 'Sydney', 'Queensland'.
       */
      stateHint: string | null
      /**
       * The sentence the newspaper was read from.
       */
      context: string | null
    } | null
    /**
     * Ids into sources.json songbooks, matched by title in the notes.
     */
    songbooks: string[]
    singers: string[]
    collectors: string[]
  }
  media: {
    midi: {
      url: string
    }[]
    images: {
      url: string
      type: string
      /**
       * 'notation': a music scan; 'masthead': the newspaper's title banner cropped from the Trove page.
       */
      role: 'notation' | 'masthead'
      width: number | null
      height: number | null
    }[]
    /**
     * MP3 recordings embedded on the page (a handful of records).
     */
    audio: {
      url: string
    }[]
  }
  location: {
    /**
     * 'newspaper': the newspaper's place of publication from the gazetteer; 'newspaper-state': only the state, from the notes' wording.
     */
    basis: 'newspaper' | 'newspaper-state' | null
    state: 'NSW' | 'VIC' | 'QLD' | 'SA' | 'WA' | 'TAS' | 'NT' | 'ACT' | 'NZ' | 'UK' | 'US' | null
    town: string | null
    lat: number | null
    lng: number | null
    placeId: string | null
    raw: string | null
  }
  related: {
    id: string
    relation: 'linked' | 'see' | 'variant'
    title: string | null
  }[]
  /**
   * Curated themes (data/themes.json); empty until curated.
   */
  themes: string[]
  warnings: string[]
}
