// Generates TypeScript types from ../data/schema/*.schema.json (json-schema-to-typescript).
// Output is committed (src/types/song.ts, place.ts, facets.ts); re-run after a schema change.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const here = dirname(fileURLToPath(import.meta.url))
const schemaDir = resolve(here, '..', '..', 'data', 'schema')
const outDir = resolve(here, '..', 'src', 'types')

const targets = [
  ['song.schema.json', 'song.ts', 'Song'],
  ['place.schema.json', 'place.ts', 'Place'],
  ['facets.schema.json', 'facets.ts', 'Facets'],
]

for (const [schemaFile, outFile, name] of targets) {
  const schema = JSON.parse(readFileSync(join(schemaDir, schemaFile), 'utf8'))
  delete schema.$id
  const ts = await compile(schema, name, {
    bannerComment: `/* eslint-disable */\n// Generated by scripts/gen-types.mjs from data/schema/${schemaFile}. Do not edit by hand.`,
    additionalProperties: false,
    strictIndexSignatures: true,
    style: { semi: false, singleQuote: true, printWidth: 110 },
  })
  writeFileSync(join(outDir, outFile), ts)
  console.log(`gen-types: wrote src/types/${outFile}`)
}
